
--  Data Quality — rules catalogue, group pipeline

-- Run once, and again whenever you add or change a check.**
--
-- ## What this is, and what it is not
-- This table **documents** every check: what it asserts, why the threshold
-- is what it is, and what Silver does about a failure.

-- Every rationale opens with one of three tags, so a reviewer can tell a
-- measurement from a default at a glance:
-- | Tag | Meaning |
-- |---|---|
-- | `[structural]` | One occurrence corrupts an aggregate, a join or the grain — or the check is scalar, where a percentage is 0 or 100 and nothing between. Threshold `0.0` is the only value that means anything. |
-- | `[tolerated]` | The source is known to be imperfect. Threshold is the policy `5.0`. Where a rate was counted it is quoted as a **baseline** — what the data does today — never as the basis for the threshold. |
-- | `[provisional]` | Never measured. The same policy `5.0`, and nobody has looked yet. |
--
-- There is no tier that derives a threshold from its own observed rate.
-- There used to be, called `[measured]`, and eleven rules sat on it. It
-- produced eleven WARNs and zero FAILs, because a limit set just above
-- its own observation is arithmetically incapable of failing on the data
-- it was fitted to. Replacing all eleven with the policy `5.0` changed no
-- verdict on this dataset, which is the proof that the fitted numbers
-- were decoration.
--
-- Query them: `WHERE rationale LIKE '[provisional]%'` lists everything
-- still waiting for a real number.
--
-- ## Two new columns
-- `threshold_pct` was doing two jobs: saying how much is tolerable, and
-- implying how serious a failure is. Those are different questions, and a
-- scalar check makes the overlap obvious -- `total_rows` is 1, so
-- `failed_pct` is 0 or 100 and the threshold carries no information at
-- all. Severity now lives on its own.
--
-- | Column | Meaning |
-- |---|---|
-- | `blocking` | TRUE if a FAIL on this rule stops the pipeline. Mirrors the `IN` list in the check notebook's gate. |
-- | `denominator_scope` | what `total_rows` counts for this rule |
--
-- `denominator_scope` exists because `total_rows` does **not** mean the
-- same thing on every row of `dq_results`, and a dashboard that assumes
-- it does will draw a chart that is wrong without looking wrong:
--
-- | Value | `total_rows` is | Example |
-- |---|---|---|
-- | `table_rows` | every row in the table | most checks |
-- | `scalar` | 1 — the check is one assertion, not a rate | `lookup_has_265_zones` |
-- | `vendor_rows` | rows for one vendor only | the charge identities |
-- | `distinct_ids` | distinct key values, not rows | `pickup_zone_exists_in_lookup` |
-- | `table_rows` | trip rows | `trips_with_unmatched_pickup_zone` |
-- | `source_rows` | rows in the landed Parquet | load fidelity |
-- | `source_files` | files in the landing directory | `every_landed_file_is_loaded` |
--
-- "3% of rows failed" and "3% of the ids in the lookup failed" are not
-- comparable numbers, and until now nothing in the results said which one
-- you were reading.
--
-- The gate still owns the blocking list
-- `blocking` here is documentation, exactly as `threshold_pct` is: the
-- running copy is the `IN` list inline in the gate, so a reviewer can see
-- what stops the pipeline without opening another table, and a missing row
-- here costs a documentation gap rather than an open gate. Section 3 is
-- the drift guard for both, and the check notebook now carries its own
-- guard for names in the gate that no check produces.
--
-- silver_action
-- | Value | Meaning in Silver |
-- |---|---|
-- | `QUARANTINE` | Blocking. Sets `dq_status = QUARANTINE`; excluded from Gold. |
-- | `FLAG` | Advisory. Row is kept, a `flag_*` column marks it. |
-- | `IGNORE` | Reported only. An assertion about the source, not about a row. |

-- Only `QUARANTINE` rules feed the 10% drop-rate gate — which is a
-- different instrument from these thresholds: an aggregate limit on how
-- much Silver discards overall, blanket on purpose.

SET TIME ZONE 'America/New_York';

USE CATALOG `nyc-mobility`;
USE SCHEMA nyc_quality;



CREATE OR REPLACE TABLE dq_rules (
    layer            STRING  COMMENT 'bronze | silver | gold',
    table_name       STRING,
    check_category   STRING  COMMENT 'completeness | uniqueness | validity | consistency | business',
    check_name       STRING  COMMENT 'matches check_name in dq_results',
    threshold_pct    DOUBLE  COMMENT 'documented here; the running copy lives inline in the check notebook',
    rule_description STRING  COMMENT 'what the check asserts, in one line',
    rationale        STRING  COMMENT 'basis tag plus why this rule and why this threshold',
    silver_action    STRING  COMMENT 'QUARANTINE | FLAG | IGNORE',
    blocking         BOOLEAN COMMENT 'TRUE if a FAIL on this rule stops the pipeline; mirrors the gate list in the check notebook',
    denominator_scope STRING COMMENT 'what total_rows counts: table_rows | scalar | vendor_rows | distinct_ids | source_rows | source_files'
)
USING DELTA
COMMENT 'Catalogue of every data quality rule, with the reasoning behind each threshold.';


INSERT OVERWRITE dq_rules
SELECT * FROM VALUES
    ('bronze', 'green_taxi', 'consistency', 'dispatch_fields_null_as_a_set', 0.0, 'The six dispatch fields are null together or not at all', '[structural] Counting how many of the six are null per row, the answer is only ever 0 or 6 - observed 114,613 rows at zero and 18,754 at six. Anything in between means the pattern changed and the Silver rules built on it need revisiting.', 'IGNORE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'dropoff_after_pickup', 5.0, 'Dropoff is not before pickup', '[provisional] One row was observed with dropoff 57 minutes before pickup, from VendorID 6. Proportional damage, so the default applies.', 'QUARANTINE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'dropoff_datetime_not_null', 0.0, 'Every trip has a dropoff timestamp', '[structural] Needed for duration and speed. A trip with no end cannot be measured.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'dropoff_zone_exists_in_lookup', 0.0, 'Every dropoff LocationID exists in taxi_zones', '[structural] As above, for the destination half.', 'FLAG', TRUE, 'distinct_ids'),
    ('bronze', 'green_taxi', 'validity', 'dropoff_zone_in_range', 5.0, 'Dropoff LocationID is between 1 and 265', '[provisional] As above, for the destination half.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'dropoff_zone_not_null', 0.0, 'Every trip has a dropoff LocationID', '[structural] As above, for the destination half of the trip.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'duration_not_zero', 5.0, 'Pickup and dropoff are not the identical instant', '[provisional] A zero-length trip is a meter fault or a cancellation. Kept separate from dropoff_after_pickup because the causes differ.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'duration_under_24_hours', 5.0, 'Trip lasts under 24 hours', '[provisional] A maximum of 2,456 minutes - about 41 hours - was observed. Almost certainly a meter left running.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'every_landed_file_is_loaded', 0.0, 'Every file in the landing directory appears in source_file', '[structural] The incremental-safe half of load fidelity. row_count_matches_source compares everything in the landing directory with everything in the table, which is only the same population while the load is a full refresh; the moment it goes incremental a not-yet-loaded file looks like row loss and archived history looks like a double load. This reconciles on source_file instead, and catches the failure a row count cannot see: COPY INTO skipping one file of three still produces a large, plausible-looking table.', 'QUARANTINE', TRUE, 'source_files'),
    ('bronze', 'green_taxi', 'validity', 'fare_amount_not_negative', 5.0, 'Fare is not negative', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. Negative fares are refunds and disputes - all observed rows carry payment_type 3 (No charge) or 4 (Dispute) - and are legitimate trips. Observed 0.29 percent. Excluded from revenue totals in Gold, kept in trip counts.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'fare_amount_not_null', 5.0, 'Every trip records a fare', '[provisional] Base of most revenue figures. Proportional damage, so the default applies. Note that for VendorID 6 fare_amount is a placeholder rather than a fare - see myle_fare_stays_placeholder.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'fare_implies_some_distance', 5.0, 'A positive fare implies non-zero distance', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. Observed 3.14 / 3.44 / 3.29 percent across March, April and May 2026 - stable month to month, so a property of the source rather than an incident. 62.9 percent of these trips last under a minute and 58.9 percent start and end in the same zone, consistent with cancelled or mis-started trips carrying a minimum charge. Threshold raised from an original estimate of 2.0, which was never measured. 4.0 clears the observed rate with room for variation while still catching a genuine jump.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'fare_plausible_for_duration', 5.0, 'No large fare on a zero-distance trip under a minute', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. A cluster of round fares on trips that barely happened: 300 appears 22 times at about 3 seconds and zero distance, 18 of them starting and ending in the same zone, plus smaller groups at 250, 200, 160 and 120. Roughly 50 rows, about 0.04 percent. Too few to move any threshold and too specific to be an accident, and it hides inside fare_implies_some_distance where 4,387 rows are mostly genuine one-minute cancellations. Threshold 0.1 because a handful is expected and a jump is not.', 'QUARANTINE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'implied_speed_under_100mph', 5.0, 'Implied average speed is under 100 mph', '[provisional] Distance divided by duration. A violation means distance or duration is wrong, not that the taxi was fast.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'ingestion_time_recorded', 5.0, 'Every row carries an ingestion timestamp', '[provisional] Lineage. Less critical than source_file because the load history is also in Delta, so the default applies.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'myle_dispatch_fields_stay_null', 0.0, 'VendorID 6 still submits no dispatch fields', '[structural] Myle is 100 percent null on all six dispatch fields across 14,181 rows. Several downstream rules are built on that being total rather than partial, so any exception invalidates them.', 'IGNORE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'myle_fare_stays_placeholder', 0.0, 'VendorID 6 fare_amount stays below 10', '[structural] Myle fare_amount is a placeholder, not a fare. Its values are small multiples of 1.5 - 0, 1.5, 3, 4.5, 6, 7.5, 9 - and its average is flat at about 2.75 across every distance band, while total_amount rises from 15.79 under a mile to 51.52 over twelve. A number uncorrelated with distance is not a metered fare, so total_amount is the real charge for these 14,181 trips and any revenue figure built on fare_amount is wrong by roughly a factor of ten for a tenth of the dataset. The bound of 10 sits above the largest observed value of 9 and far below the average total of 29: crossing it means Myle started reporting real fares and Silver needs to know. An earlier version asserted fare_amount IN (0, 3) from about twenty visible rows and failed on 1,537 of them - never generalise a domain from a LIMIT 20.', 'IGNORE', FALSE, 'vendor_rows'),
    ('bronze', 'green_taxi', 'uniqueness', 'no_exact_duplicate_rows', 5.0, 'No two rows identical across all trip columns', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. There is no trip id in this dataset, so two identical rows may be two genuine trips that happen to share every value. 1.0 reflects that this is a judgement rather than a defect count.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_congestion_surcharge', 0.0, 'The load added no nulls to congestion_surcharge', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_do_location_id', 0.0, 'The load added no nulls to DOLocationID', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_dropoff_datetime', 0.0, 'The load added no nulls to lpep_dropoff_datetime', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_extra', 0.0, 'The load added no nulls to extra', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_fare_amount', 0.0, 'The load added no nulls to fare_amount', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_improvement_surcharge', 0.0, 'The load added no nulls to improvement_surcharge', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_mta_tax', 0.0, 'The load added no nulls to mta_tax', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_passenger_count', 0.0, 'The load added no nulls to passenger_count', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_payment_type', 0.0, 'The load added no nulls to payment_type', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_pickup_datetime', 0.0, 'The load added no nulls to lpep_pickup_datetime', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_pu_location_id', 0.0, 'The load added no nulls to PULocationID', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_ratecode_id', 0.0, 'The load added no nulls to RatecodeID', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_store_and_fwd_flag', 0.0, 'The load added no nulls to store_and_fwd_flag', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_tip_amount', 0.0, 'The load added no nulls to tip_amount', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_tolls_amount', 0.0, 'The load added no nulls to tolls_amount', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_total_amount', 0.0, 'The load added no nulls to total_amount', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_trip_distance', 0.0, 'The load added no nulls to trip_distance', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_trip_type', 0.0, 'The load added no nulls to trip_type', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_vendor_id', 0.0, 'The load added no nulls to VendorID', '[structural] The group load declares its schema and CASTs, so there is no _rescued_data and a failed cast is indistinguishable from a missing value. The landed Parquet is the last copy that has not been cast: a column with more nulls after the load than before it lost data in the cast. Self-inflicted loss, so zero tolerance regardless of tier. Every cast column is compared, not the handful that seemed most likely to break - a cast that silently nulls a value is invisible by definition, so likely is not something you can know in advance, and the extra columns cost nothing because it is the same single pass over the same files.', 'QUARANTINE', TRUE, 'source_rows'),
    ('bronze', 'green_taxi', 'business', 'no_tip_recorded_on_cash', 5.0, 'Cash trips record no tip', '[provisional] Cash tips are famously unrecorded by the meter, so a non-zero tip on payment_type 2 is a data-entry oddity rather than a fraud signal.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'passenger_count_not_negative', 0.0, 'Passenger count is not negative', '[structural] A negative integer casts cleanly, so it passes every type check while being impossible. Nothing downstream can interpret it.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'passenger_count_not_null_excl_myle', 5.0, 'Passenger count present, excluding VendorID 6', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. Myle Technologies submits none of the six dispatch fields, so its nulls are structural rather than missing data and are excluded here. 5.0 covers the genuine gaps observed from the other two vendors: 1.66 percent for VendorID 1 and 4.05 percent for VendorID 2.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'passenger_count_not_zero', 5.0, 'Passenger count is not an explicit 0', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. Different from NULL: the meter recorded a value and that value was nobody. Observed 1,727 rows, 1.29 percent.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'passenger_count_plausible', 5.0, 'Passenger count is 9 or fewer', '[provisional] Green taxis seat at most a handful. Higher values indicate a meter or entry fault. Proportional damage, default threshold.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'payment_type_in_domain', 5.0, 'payment_type is 0 to 6', '[provisional] 0 Flex Fare, 1 Credit card, 2 Cash, 3 No charge, 4 Dispute, 5 Unknown, 6 Voided. Code 0 is a recent addition an older dictionary does not list.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'pickup_datetime_not_null', 0.0, 'Every trip has a pickup timestamp', '[structural] The grain of the whole dataset is a trip in time. Without this the row cannot be placed on any date axis, so no percentage of it is tolerable.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'pickup_month_matches_source_file', 5.0, 'Pickup falls in the months we loaded', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. TLC files reliably carry a few trips dated years outside the file month. Observed 11 rows, 0.008 percent, including trips dated 2008 and 2009. Kept at 0.5 rather than the provisional default because 5.0 would tolerate over six thousand out-of-window trips and make the check decorative.', 'QUARANTINE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'pickup_zone_exists_in_lookup', 0.0, 'Every pickup LocationID exists in taxi_zones', '[structural] Measured in distinct ids, not trips: one unmatched id affecting forty thousand trips is one thing to fix, and reporting it as forty thousand failures would drown out everything else. An unmatched id becomes an Unknown member in dim_zone, so the trip survives but lands in a bucket nobody can act on.', 'FLAG', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'pickup_zone_in_range', 5.0, 'Pickup LocationID is between 1 and 265', '[provisional] An out-of-range id cannot join to the zone lookup and lands in the Unknown member. Proportional damage.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'pickup_zone_not_null', 0.0, 'Every trip has a pickup LocationID', '[structural] The only location information in the file. Required for any zone-level question and for the dim_zone join.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'ratecode_in_domain', 5.0, 'RatecodeID is 1 to 6 or 99', '[provisional] From the TLC LPEP dictionary. Re-check when TLC republishes it.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'row_count_matches_source', 0.0, 'Bronze row count equals the landed Parquet row count', '[structural] Whether our own pipeline dropped or duplicated rows on the way in, not how imperfect the source is. There is no tolerable rate of self-inflicted loss. A failure means COPY INTO skipped a file it had already loaded, or loaded one twice.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'source_file_recorded', 0.0, 'Every row carries its source file', '[structural] Lineage. Without it a bad month cannot be traced back to the file it came from, and no per-file investigation is possible.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'store_and_fwd_flag_in_domain', 5.0, 'store_and_fwd_flag is Y or N', '[provisional] Nulls are handled by the dispatch-field checks rather than counted here.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'table_not_empty', 0.0, 'The table holds at least one row', '[structural] Scalar check. An empty table makes every SUM(CASE ...) in the metrics block NULL, and a NULL failed_rows falls through the status CASE to FAIL - so an empty load already stops the pipeline, but by accident, and reported as forty unrelated failures rather than one cause. This states it on purpose so the results list opens with the reason instead of the symptoms. silver_action is IGNORE because there is no row to act on - if the table is empty there is nothing in it to quarantine.', 'IGNORE', TRUE, 'scalar'),
    ('bronze', 'green_taxi', 'validity', 'total_amount_not_negative', 5.0, 'Total is not negative', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. Same reasoning as fare_amount_not_negative, and the same rows.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'total_amount_not_null', 5.0, 'Every trip records a total', '[provisional] Reported directly in Gold and the only trustworthy charge column for VendorID 6. Proportional damage.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'business', 'total_equals_sum_of_charges_v1', 5.0, 'For VendorID 1, total_amount equals fare plus extra plus mta_tax plus tip plus tolls', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. VendorID 1 (Creative Mobile) reports total_amount as fare plus extra plus mta_tax plus tip plus tolls. It still contains tip and tolls, so this is not the metered fare - it is everything except the three surcharges. All three surcharges - improvement, congestion and cbd_congestion_fee - are itemised in their own columns but never rolled in. Established in two steps: dropping improvement and congestion took the mismatch from 95.74 to 12.09 percent, and the remainder then sat on a single residual of -0.75 across 1,114 rows, which is the cbd fee. With all three excluded, 98.37 percent reconcile. Threshold 2.0 against the observed 1.63 percent.', 'QUARANTINE', FALSE, 'vendor_rows'),
    ('bronze', 'green_taxi', 'business', 'total_equals_sum_of_charges_v2', 5.0, 'For VendorID 2, total_amount equals the sum of its components', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. VendorID 2 (Curb) is the only vendor reporting a full fare decomposition. cbd_congestion_fee must be included: it is a flat 0.75 Congestion Relief Zone charge, and omitting it from an earlier version of this formula produced a 26 percent failure rate across all vendors that looked like a data fault and was a missing column. With it included, 98.67 percent reconcile. The residual 1.33 percent is 1,444 rows of which 1,316 sit on a single value of 2.75 - a congestion surcharge collected but not itemised, which is a source inconsistency rather than a missing term. Threshold 2.0 sits just above the measured rate.', 'QUARANTINE', FALSE, 'vendor_rows'),
    ('bronze', 'green_taxi', 'validity', 'trip_distance_not_negative', 0.0, 'Distance is not negative', '[structural] Physically impossible. A negative here means a corrupt record, not a refund.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'trip_distance_not_null', 5.0, 'Every trip records a distance', '[provisional] Used in speed, revenue-per-mile and disruption analysis. Damage is proportional - a null affects that trip and nothing else - so the default 5.0 applies until the real rate is counted.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'trip_distance_plausible', 5.0, 'Trip distance is plausible (under 200 miles)', '[tolerated] A single trip of 111,005 miles was observed; p99.9 is 31 miles, so 200 sits far above real trips and far below the fault. Policy 5.0 rather than 0.0 because 200 is a PLAUSIBILITY cutoff: the row arrived and is recorded correctly, which makes it a source imperfection. A negative distance is impossible and is the one that carries 0.0 and blocks. At 0.0 this reported FAIL on 31 of 133,367 rows and would have on every run forever, which is the definition of a check people stop reading. The realistic blow-up -- a feed switching to metres -- lands near 100 percent and is caught easily.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'trip_type_in_domain', 5.0, 'trip_type is 1 or 2', '[provisional] 1 street-hail, 2 dispatch.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'trips_with_unmatched_dropoff_zone', 100.0, 'Trip rows whose dropoff LocationID is not in the lookup', '[structural] ADVISORY. As above, for the destination half.', 'IGNORE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'consistency', 'trips_with_unmatched_pickup_zone', 100.0, 'Trip rows whose pickup LocationID is not in the lookup', '[structural] ADVISORY - threshold 100.0 so it can only ever WARN, because it is the same defect as pickup_zone_exists_in_lookup measured a second way and one defect should not be able to stop the pipeline twice. The key count is what you act on: one unmatched id is one thing to fix whether it touches six trips or sixty thousand. This is what tells you how much it costs, and the two numbers can be four orders of magnitude apart.', 'IGNORE', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'validity', 'vendor_id_in_domain', 5.0, 'VendorID is 1, 2 or 6', '[provisional] From the current TLC LPEP dictionary: 1 Creative Mobile, 2 Curb Mobility, 6 Myle Technologies. An earlier version of this check used (1,2) from an older dictionary and flagged 14,181 valid Myle trips as invalid. A domain check is only as current as the dictionary it was copied from.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'green_taxi', 'completeness', 'vendor_id_not_null', 5.0, 'Every trip names its LPEP provider', '[provisional] Provenance. Needed to interpret the dispatch-field gaps and to pick the right charge identity.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'business', 'airport_zones_present', 0.0, 'LocationIDs 1, 132 and 138 are all present', '[structural] Scalar check. Newark, JFK and LaGuardia. If these are missing the file is not the lookup we think it is.', 'IGNORE', FALSE, 'scalar'),
    ('bronze', 'taxi_zones', 'validity', 'borough_in_domain', 5.0, 'Borough is one of the eight published values', '[provisional] Manhattan, Queens, Brooklyn, Bronx, Staten Island, EWR, Unknown, N/A. A new value means the lookup changed shape.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'completeness', 'borough_not_null', 5.0, 'Every zone names a borough', '[provisional] Used for every borough-level rollup in Gold.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'validity', 'location_id_in_range', 5.0, 'LocationID is between 1 and 265', '[provisional] The published lookup uses 1 to 265 inclusive.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'completeness', 'location_id_not_null', 0.0, 'Every zone row has a LocationID', '[structural] The primary key of the lookup. A null key joins to nothing.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'taxi_zones', 'uniqueness', 'location_id_unique', 0.0, 'LocationID is unique across the lookup', '[structural] The single most important check on this table: a duplicate key fans out the trip join in Gold and inflates every count in that zone. Counted as COUNT(location_id) - COUNT(DISTINCT location_id), not COUNT(*) - COUNT(DISTINCT location_id): COUNT(DISTINCT x) ignores nulls, so the COUNT(*) form reports every null key as a duplicate key. Two different defects with two different fixes, and the null one already has its own check.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'taxi_zones', 'business', 'lookup_has_265_zones', 0.0, 'The lookup holds exactly 265 zones', '[structural] Scalar check - total_rows is 1, so the percentage is 0 or 100 and nothing in between, which makes any non-zero threshold behave exactly like zero. A different count means the file changed or the load is partial, and every zone-level result downstream is suspect.', 'IGNORE', FALSE, 'scalar'),
    ('bronze', 'taxi_zones', 'validity', 'service_zone_in_domain', 5.0, 'Service zone is one of the five published values', '[provisional] Boro Zone, Yellow Zone, Airports, EWR, N/A.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'completeness', 'service_zone_not_null', 5.0, 'Every zone names a service zone', '[provisional] Distinguishes Boro Zone, Yellow Zone, Airports and EWR.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'completeness', 'table_not_empty', 0.0, 'The table holds at least one row', '[structural] Scalar check. As above. On the lookup it is worse than on the fact table: an empty taxi_zones makes every referential-integrity check report 100 percent unmatched, which looks like a trip-data problem.', 'IGNORE', TRUE, 'scalar'),
    ('bronze', 'taxi_zones', 'completeness', 'zone_name_not_null', 5.0, 'Every zone has a name', '[provisional] The human-readable label on every zone-level report.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'business', 'zone_names_shared_is_3', 100.0, 'Exactly 3 LocationIDs share a zone name', '[structural] Scalar check, ADVISORY - threshold 100.0 so it can only ever WARN. Expect exactly 3: LocationIDs 103, 104 and 105 all carry the name Governors Island/Ellis Island/Liberty Island. Group by id and you get three rows; group by name and you get one. Neither is wrong, but a report that switches between them without saying so is. 264 and 265 are excluded because both are literally named Unknown by design. Asserted as an equality rather than as a count of offending rows: reporting the raw count meant the expected, known-good pattern produced a WARN on every single run, and a check that can never be clean is a check people learn to scroll past.', 'IGNORE', FALSE, 'scalar'),
    ('bronze', 'weather', 'completeness', 'apparent_temp_not_null', 5.0, 'Apparent temperature is present', '[provisional] Secondary to temperature_2m.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'apparent_temp_parses', 5.0, 'apparent_temperature converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'cloud_cover_0_to_100', 5.0, 'Cloud cover is a percentage', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'cloud_cover_not_null', 5.0, 'Cloud cover is present', '[provisional] Percentage cover.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'cloud_cover_parses', 5.0, 'cloud_cover converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'date_not_null', 0.0, 'Every weather row has a timestamp', '[structural] The grain and the MERGE key. A null here cannot be placed in time and cannot be matched on a re-run.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'date_parses', 0.0, 'The date column converts to a timestamp', '[structural] As above. The group table stores every column as STRING, so a value can be present and meaningless - n/a, an empty string, a dash - and a null check will happily pass it.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'weather', 'consistency', 'gusts_at_least_wind_speed', 5.0, 'Gust is at least the sustained wind speed', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. Observed 13 rows of 2,208, 0.59 percent. Raised from an original guess of 0.1. A gust cannot really be below the sustained wind, but the two are measured over different intervals and rounded independently, so near-ties are expected. A genuine column swap would show as tens of percent.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'hour_within_covered_months', 0.0, 'Hour falls inside March to May 2026', '[tolerated] Threshold is the policy 5.0, not a number derived from this rate. The observed rate below is recorded as a BASELINE - what the data does today - and is deliberately not the basis for the threshold: a limit set just above its own observation cannot fail on the data it was fitted to. A single boundary row at 2026-02-28 23:00 is produced by the timestamp reconstruction, so a small tolerance applies. 1 of 2,208 rows is 0.045 percent, which lands as WARN rather than FAIL. Silver filters to the window.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'consistency', 'month_agrees_with_date', 5.0, 'The month column agrees with the timestamp', '[provisional] Accepts either convention - 2026-03 or 3 - because the group convention is not documented; it fails only if the value agrees with neither.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'month_not_null', 5.0, 'The month column is present', '[provisional] Group table only. Partition-style column carried from the source file.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'uniqueness', 'one_row_per_hour', 0.0, 'One row per parsed hour', '[structural] The MERGE key. The load uses WHEN NOT MATCHED THEN INSERT on date, so a duplicate means the merge condition is not doing what it is supposed to. Counted over the PARSED timestamp, not the raw string: the column is text, and 2026-03-01 05:00:00+00:00 and 2026-03-01 00:00:00-05:00 are the same hour written two ways, which a string comparison calls distinct. Counted with COUNT(x) rather than COUNT(*) so an unparseable timestamp is not reported as a duplicate hour - date_parses already owns that.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'precip_probability_0_to_100', 5.0, 'Precipitation probability is a percentage', '[provisional] Open-Meteo returns 0 to 100.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'precip_probability_not_null', 5.0, 'Precipitation probability is present', '[provisional] Forecast-side field, less central than observed precipitation.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'precip_probability_parses', 5.0, 'precipitation_probability converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'rain_not_negative', 5.0, 'Rain is not negative', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'rain_not_null', 5.0, 'Rain is present', '[provisional] The group table has rain where the personal one has precipitation. Gold precip_band must be built from this column.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'rain_parses', 5.0, 'rain converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'consistency', 'source_file_is_not_placeholder', 100.0, 'source_file_month is not an unsubstituted placeholder', '[structural] ADVISORY - threshold 100.0 so it can only ever WARN. Observed 2,208 of 2,208, 100 percent: every row carries the literal text {weather_file} because the MERGE ran as plain SQL rather than through Python string formatting, so lineage for this table is gone. This is a real defect and the number is not tolerable. It is advisory because the fix belongs to the loader rather than to quality checks, and blocking the whole Bronze gate on another team''s bug helps nobody. Reported every run so it stays visible; set the threshold back to 0.0 once it is fixed.', 'IGNORE', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'table_not_empty', 0.0, 'The table holds at least one row', '[structural] Scalar check. As above.', 'IGNORE', TRUE, 'scalar'),
    ('bronze', 'weather', 'completeness', 'temperature_not_null', 5.0, 'Temperature is present', '[provisional] Feeds temp_band in the Gold weather dimension. Proportional damage.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'temperature_parses', 5.0, 'temperature_2m converts to a number', '[provisional] The group table is entirely STRING, so each numeric column needs a parse check alongside its null check.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'temperature_plausible', 5.0, 'Temperature is between -30 and 50', '[provisional] Assumes Open-Meteo metric defaults (Celsius). Verify with the units cell before trusting this: if the request used Fahrenheit every threshold here is wrong and the results still look reasonable.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'visibility_not_negative', 5.0, 'Visibility is not negative', '[provisional] Metres in the metric default.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'visibility_not_null', 5.0, 'Visibility is present', '[provisional] Feeds visibility_band and the is_adverse flag in Gold.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'visibility_parses', 5.0, 'visibility converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'weather_code_in_wmo_domain', 5.0, 'Weather code is an integral WMO 4677 code', '[provisional] Two conditions, and the integrality test is not decoration: Spark truncates DOUBLE to INT, so CAST(3.5 AS INT) is 3 and 3 is a valid code. Without it a fractional value - exactly what a botched unit conversion or a half-written interpolation produces - is silently rounded into the allowed set and the check reports clean. Parsed as DOUBLE first: try_cast(''3.0'' AS INT) is NULL, and an earlier version casting straight to INT made this check pass because it was broken, since NULL NOT IN (...) is NULL rather than TRUE.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'weather_code_not_null', 5.0, 'WMO weather code is present', '[provisional] The categorical description of the hour.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'weather_code_parses', 5.0, 'weather_code converts to a number', '[provisional] Parsed as DOUBLE, not INT. A CSV that writes a code as 3.0 fails try_cast to INT outright: an earlier version reported 100 percent of rows unparseable when the data was fine and the check was wrong.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'wind_gusts_not_null', 5.0, 'Wind gusts are present', '[provisional] Paired with wind_speed.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'wind_gusts_parses', 5.0, 'wind_gusts_10m converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'wind_speed_not_negative', 5.0, 'Wind speed is not negative', '[provisional] km/h in the metric default.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'wind_speed_not_null', 5.0, 'Wind speed is present', '[provisional] Feeds wind_band.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'validity', 'wind_speed_parses', 5.0, 'wind_speed_10m converts to a number', '[provisional] As above.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'taxi_zones', 'completeness', 'source_file_recorded', 0.0, 'Every row carries its source file', '[structural] Lineage. Without it a bad load cannot be traced back to the file it came from, and no per-file investigation is possible. Blocking in the gate, like green_taxi''s.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'taxi_zones', 'completeness', 'ingestion_time_recorded', 5.0, 'Every row carries its ingestion time', '[tolerated] Useful rather than load-bearing: it answers when a row landed without re-reading the volume. Policy 5.0.', 'FLAG', FALSE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'source_file_recorded', 0.0, 'Every row carries its source file', '[structural] Lineage. Without it a bad load cannot be traced back to the file it came from, and no per-file investigation is possible. Blocking in the gate, like green_taxi''s.', 'QUARANTINE', TRUE, 'table_rows'),
    ('bronze', 'weather', 'completeness', 'ingestion_time_recorded', 5.0, 'Every row carries its ingestion time', '[tolerated] Useful rather than load-bearing: it answers when a row landed without re-reading the volume. Policy 5.0.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'business', 'charges_reconcile_by_vendor', 5.0, 'Charge components sum to total_amount, per vendor', '[tolerated] The three providers report total_amount differently. Computed at check time from the component columns rather than stored, so the rule can be corrected without a schema migration and without a stored value going stale against the rule that produced it. Vendor 6 does not decompose its charges at all and is excluded from both sides of the rate. Observed 1.63 percent for vendor 1 and 1.33 for vendor 2 - a BASELINE, not the basis for the threshold. NOTE: the Silver cleaning inflates this. tip_amount is zeroed on cash payments while total_amount still contains the tip, and the negative clamps break the identity on refunds (payment_type 3 and 4), where the negative components are what make the negative total add up. If this check goes over threshold, read 41_silver_green_taxi_group before blaming the source.', 'FLAG', FALSE, 'vendor_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'dedup_removal_rate', 5.0, 'The dedup removed a small share of Bronze', '[tolerated] The reconciliation remainder expressed as a rate, so a dedup that suddenly eats a third of the table is visible as a number rather than as a silent success. Threshold is the policy 5.0.', 'FLAG', FALSE, 'source_rows'),
    ('silver', 'green_taxi_clean', 'validity', 'dq_status_in_domain', 0.0, 'dq_status is PASS, WARN or FAIL', '[structural] dq_status has exactly three states. A fourth value means the CASE that derives it was edited into a shape nobody intended, and every view filtering on it is then quietly wrong.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'completeness', 'dq_status_populated', 0.0, 'Every row carries a dq_status', '[structural] A null status puts the row in NEITHER view - not valid, not quarantined - which is deliberate: defaulting it either way hides the bug. Ships unchecked data one way, claims a reason that was never computed the other.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'dropoff_zone_exists_in_lookup', 0.0, 'Every dropoff LocationID resolves to a zone', '[structural] As above, for the destination half.', 'QUARANTINE', TRUE, 'distinct_ids'),
    ('silver', 'green_taxi_clean', 'consistency', 'every_bronze_file_present', 0.0, 'Every Bronze file produced Silver rows', '[structural] Scalar check, reconciled by NAME rather than by count: two files of the same size reconcile by count while one of them never loaded. A Bronze file with no Silver rows has not been through the cleaning, and Gold is about to be built without it.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'green_taxi_clean', 'consistency', 'fail_rows_carry_a_fail_issue', 0.0, 'A FAIL row carries at least one FAIL: entry', '[structural] A quarantined row with no reason cannot be defended to a reviewer, and the quarantine view has nothing to show for it.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'completeness', 'ingestion_time_recorded', 5.0, 'Every row carries its Bronze ingestion time', '[tolerated] Useful rather than load-bearing: it answers when a row landed in Bronze without re-reading Bronze. Policy 5.0.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'null_timestamps_are_quarantined', 0.0, 'Every row with a null pickup or dropoff is marked FAIL', '[structural] Nothing is deleted in this pipeline, so the assertion is not that no bad row survived - it is that every bad row is LABELLED. A row with a null pickup and dq_status WARN is real, invisible, and flows into Gold through the valid view as though it were fine.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'uniqueness', 'one_row_per_merge_key', 0.0, 'The merge key is unique in the target', '[structural] The merge key must be unique in the TARGET, or the MERGE updates the same row more than once per run and every Gold join fans out.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'out_of_era_pickups_are_quarantined', 0.0, 'Every pre-2009 or future pickup is marked FAIL', '[structural] LPEP started in 2009, so a pickup before it cannot be a real record. TLC files reliably carry a few trips dated years away.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'pass_rows_carry_no_issues', 0.0, 'A PASS row has an empty issue list', '[structural] Impossible if the derivation is right, which is exactly why it is worth asserting. A check that can only fail when the code is broken is the cheapest regression test there is.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'pickup_zone_exists_in_lookup', 0.0, 'Every pickup LocationID resolves to a zone', '[structural] Measured in distinct ids: one unmatched id is one thing to fix whether it touches six trips or sixty thousand. An id with no zone becomes an Unknown member in dim_zone - the trip survives and lands in a bucket labelled we do not know where, so the star schema works perfectly and the answer is quietly wrong. Read from vw_green_taxi_valid, not the table: a quarantined row''s unresolvable zone has already been handled.', 'QUARANTINE', TRUE, 'distinct_ids'),
    ('silver', 'green_taxi_clean', 'completeness', 'qc_array_not_null', 0.0, 'qc_error_descriptions is never NULL', '[structural] size(NULL) is NULL, so a null array makes the whole derivation return NULL rather than a status. Completeness on a column Silver produces.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'validity', 'qc_entries_carry_severity_prefix', 0.0, 'Every issue entry starts with FAIL: or WARN:', '[structural] The whole design rests on the prefix: dq_status is derived from it, and a forgotten seven characters silently downgrades a FAIL row to WARN. This is the check that turns that omission into a visible failure instead of a wrong answer.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'business', 'quarantine_rate_within_limit', 5.0, 'Under 5 percent of trips are quarantined', '[tolerated] The one blanket limit. Every per-check threshold asks whether one rule is violated too often; only this one asks whether we are excluding so much that the answer stops being about New York taxis. Ten rules each quarantining 2 percent would all pass and between them remove a fifth. If it fires, read vw_green_taxi_quarantined before assuming the data is at fault - this is also the check most likely to catch a rule that is too aggressive.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'revenue_preserved', 0.0, 'Total revenue survives the cleaning', '[structural] Scalar check. A cast or a rename that damaged a numeric column shows up here and almost nowhere else - row counts would still reconcile perfectly.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'green_taxi_clean', 'consistency', 'reversed_trips_are_quarantined', 0.0, 'Every row with dropoff before pickup is marked FAIL', '[structural] A negative duration corrupts every average it reaches. As above: the fault is the missing label, not the surviving row.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'business', 'rows_carrying_a_warning', 100.0, 'How many trips carry at least one warning', '[advisory] ADVISORY at 100.0, so it can only ever WARN. A number in the run log every run beats a sentence in a comment once.', 'IGNORE', FALSE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'rows_reconcile_with_bronze', 0.0, 'Silver equals Bronze minus the dedup', '[structural] Scalar check. The only check that can catch a WHERE creeping into a transformation, because every other check looks at what survived. Deliberately not silver = bronze: the dedup is supposed to remove rows, so the assertion is that the number removed equals the number of duplicate merge keys and not one more.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'green_taxi_clean', 'completeness', 'silver_at_recorded', 0.0, 'Every row records when it was cleaned', '[structural] Completeness on a column Silver alone is responsible for producing. It is what distinguishes rule changed from data changed when two runs disagree.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'completeness', 'source_file_recorded', 0.0, 'Every row carries its source file', '[structural] Lineage. Bronze treats this as blocking; dropping the column at Silver undoes that gate, and a bad month can no longer be traced back to the file it came from. It is also what the file-reconciliation check joins on.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'completeness', 'table_not_empty', 0.0, 'The table holds at least one row', '[structural] Scalar check. An empty table makes every SUM(CASE ...) NULL, and a NULL failed_rows falls through the status CASE to FAIL - loud, but by accident, and reported as dozens of unrelated failures rather than one cause.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'green_taxi_clean', 'consistency', 'trip_hour_has_weather', 5.0, 'Every trip hour finds a weather row', '[tolerated] Every trip hour must find a weather row, and the failure mode is not a null - it is a silently WRONG match, which is what happens when the session timezone is UTC rather than America/New_York. Bronze caught that once: 1 March held 20 hours under UTC bucketing, and every trip would have matched weather four hours away with no error anywhere. Pickups outside the loaded window are WARN rather than FAIL, so they stay in the valid view and a handful of hours legitimately have none.', 'FLAG', FALSE, 'distinct_ids'),
    ('silver', 'green_taxi_clean', 'consistency', 'trips_with_unmatched_dropoff_zone', 100.0, 'How many trip rows have an unresolvable dropoff zone', '[advisory] ADVISORY at 100.0. As above, for the destination half.', 'IGNORE', FALSE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'trips_with_unmatched_pickup_zone', 100.0, 'How many trip rows have an unresolvable pickup zone', '[advisory] ADVISORY at 100.0. The same defect as pickup_zone_exists_in_lookup counted in trips rather than keys - three zones and eight thousand trips are different sentences and a reviewer wants both. One defect should not stop the pipeline twice, so only the key-level check blocks.', 'IGNORE', FALSE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'unresolvable_zones_are_quarantined', 0.0, 'Every row with an unusable zone is marked FAIL', '[structural] A zone outside 1..265 or null has no lookup row to join to, so the trip has no spatial axis. As above: the fault is the missing label.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'untraceable_rows_are_quarantined', 0.0, 'Every row without a source file is marked FAIL', '[structural] Bronze treats source_file_recorded as blocking. A row that cannot be traced back to its file cannot be defended, and dropping the lineage at Silver would undo that gate.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'consistency', 'warn_rows_carry_only_warn_issues', 0.0, 'A WARN row carries issues, none of them FAIL:', '[structural] Catches both directions at once: a WARN row with no issues at all, and a WARN row that should have been FAIL.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'green_taxi_clean', 'validity', 'zones_within_1_to_265', 0.0, 'Pickup and dropoff zones are between 1 and 265', '[structural] Bronze uses 1..265, so Silver must too. A narrower range in the cleaning makes Bronze and Silver disagree about what a valid zone is, and rewrites a legitimate 265 into something else.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'business', 'airport_zones_present', 0.0, 'All three airport zones are present', '[structural] Scalar check. Zones 1, 132 and 138 are Newark, JFK and LaGuardia, and the airport split in Gold is built on them.', 'QUARANTINE', FALSE, 'scalar'),
    ('silver', 'taxi_zones_clean', 'validity', 'borough_in_domain', 0.0, 'Borough is one of the six published values', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'completeness', 'borough_not_blank', 0.0, 'Borough is present and not blank', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'validity', 'location_id_in_range', 0.0, 'LocationID is between 1 and 265', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'completeness', 'location_id_not_null', 0.0, 'Every lookup row has a LocationID', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'uniqueness', 'location_id_unique', 0.0, 'LocationID is unique in the lookup', '[structural] Counted as COUNT(x) - COUNT(DISTINCT x), not COUNT(*) - COUNT(DISTINCT x): COUNT(DISTINCT) ignores nulls, so the COUNT(*) form reports a null key as a duplicate key - two different defects with two different fixes, and the null one already has its own check.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'business', 'lookup_has_265_zones', 0.0, 'The lookup holds exactly 265 zones', '[structural] Scalar check. The TLC lookup publishes 265 zones. A different number means the lookup version changed and the zone handling built on it needs revisiting.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'taxi_zones_clean', 'consistency', 'rows_reconcile_with_bronze', 0.0, 'Silver equals Bronze minus the dedup', '[structural] Scalar check. The only check that can catch a WHERE creeping into a transformation, because every other check looks at what survived. Deliberately not silver = bronze: the dedup is supposed to remove rows, so the assertion is that the number removed equals the number of duplicate merge keys and not one more.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'taxi_zones_clean', 'validity', 'service_zone_in_domain', 0.0, 'Service zone is one of the five published values', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'completeness', 'service_zone_not_blank', 0.0, 'Service zone is present and not blank', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'completeness', 'source_file_recorded', 0.0, 'Every row carries its source file', '[structural] Lineage. Bronze treats this as blocking; dropping the column at Silver undoes that gate, and a bad month can no longer be traced back to the file it came from. It is also what the file-reconciliation check joins on.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'taxi_zones_clean', 'completeness', 'table_not_empty', 0.0, 'The table holds at least one row', '[structural] Scalar check. An empty table makes every SUM(CASE ...) NULL, and a NULL failed_rows falls through the status CASE to FAIL - loud, but by accident, and reported as dozens of unrelated failures rather than one cause.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'taxi_zones_clean', 'business', 'two_unknown_zones_present', 0.0, 'Both unknown zones, 264 and 265, are present', '[structural] Scalar check. 264 and 265 are the source saying the meter did not record a zone. Silver is where they most often get lost - a BETWEEN 1 AND 263 written anywhere in the cleaning removes them, and then every trip with an unrecorded zone has nothing to join to.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'taxi_zones_clean', 'completeness', 'zone_name_not_blank', 0.0, 'Zone name is present and not blank', '[structural] Scalar or structural: one occurrence corrupts a join, a grain or an aggregate, so no rate is tolerable.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'business', 'all_expected_days_present', 0.0, 'Every day of every covered month is present', '[structural] Scalar check. A generated calendar over the covered months rather than a count of distinct days: a count cannot say WHICH day is absent, and a stray boundary day can make the total look right while a real day is missing.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'weather_clean', 'validity', 'cloud_cover_0_to_100', 5.0, 'Cloud cover is a percentage', '[tolerated] Tolerated source imperfection at the policy threshold. No number here is derived from its own observed rate.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'consistency', 'description_known_for_code', 0.0, 'A known weather code has a real description', '[structural] The description is computed in Silver from the code rather than arriving from the source, so it can drift in a way a real source column cannot - and Gold''s wet/dry split reads one of the two. A known code with the description Unknown is a gap in the lookup.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'consistency', 'description_matches_code', 0.0, 'A null weather code has no invented description', '[structural] The other half: a description on a row with no code is a default that fired wrongly. Two different fixes, so two checks.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'dq_status_in_domain', 0.0, 'dq_status is PASS, WARN or FAIL', '[structural] dq_status has exactly three states. A fourth value means the CASE that derives it was edited into a shape nobody intended, and every view filtering on it is then quietly wrong.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'completeness', 'dq_status_populated', 0.0, 'Every row carries a dq_status', '[structural] A null status puts the row in NEITHER view - not valid, not quarantined - which is deliberate: defaulting it either way hides the bug. Ships unchecked data one way, claims a reason that was never computed the other.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'consistency', 'fail_rows_carry_a_fail_issue', 0.0, 'A FAIL row carries at least one FAIL: entry', '[structural] A quarantined row with no reason cannot be defended to a reviewer, and the quarantine view has nothing to show for it.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'consistency', 'gusts_at_least_wind_speed', 5.0, 'A gust is not below the sustained wind speed', '[tolerated] A gust is by definition a peak of the wind, so it cannot sit below the sustained speed. The two are measured over different intervals and rounded independently, which is where the handful of violations come from. A column swap would show up as tens of percent.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'hour_within_covered_months', 0.0, 'Every hour belongs to a month the load covers', '[structural] The window is DERIVED from the load - a month counts as covered when at least two of its days arrived - not written into the check. A window written into a check asserts something about the data, so it goes stale and produces false failures the first time a different month is loaded. This is the same fix Bronze already carries.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'uniqueness', 'one_row_per_hour', 0.0, 'One weather row per hour', '[structural] Counted over the PARSED timestamp, not the raw string: two spellings of the same instant are distinct as strings, and a duplicate hour fans out the trip-to-weather join in Gold.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'consistency', 'pass_rows_carry_no_issues', 0.0, 'A PASS row has an empty issue list', '[structural] Impossible if the derivation is right, which is exactly why it is worth asserting. A check that can only fail when the code is broken is the cheapest regression test there is.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'precip_probability_0_to_100', 5.0, 'Precipitation probability is a percentage', '[tolerated] Tolerated source imperfection at the policy threshold. No number here is derived from its own observed rate.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'completeness', 'qc_array_not_null', 0.0, 'qc_error_descriptions is never NULL', '[structural] size(NULL) is NULL, so a null array makes the whole derivation return NULL rather than a status. Completeness on a column Silver produces.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'rain_not_negative', 5.0, 'Rain is not negative', '[tolerated] Tolerated source imperfection at the policy threshold. No number here is derived from its own observed rate.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'rain_parsed', 0.0, 'Rain survived the conversion from text', '[structural] Bronze weather is entirely text, so this is the try_cast equivalent of a load-fidelity check: a NULL here on a value that was present in Bronze is a conversion we lost. Kept separate from the range checks because out of range and not a number have different fixes.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'consistency', 'rows_reconcile_with_bronze', 0.0, 'Silver equals Bronze minus the dedup', '[structural] Scalar check. The only check that can catch a WHERE creeping into a transformation, because every other check looks at what survived. Deliberately not silver = bronze: the dedup is supposed to remove rows, so the assertion is that the number removed equals the number of duplicate merge keys and not one more.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'weather_clean', 'completeness', 'silver_at_recorded', 0.0, 'Every row records when it was cleaned', '[structural] Completeness on a column Silver alone is responsible for producing. It is what distinguishes rule changed from data changed when two runs disagree.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'completeness', 'source_file_month_is_real', 100.0, 'source_file_month holds a filename, not a placeholder', '[advisory] ADVISORY at 100.0, so it can only WARN. Bronze measured this at 100 percent because the loader wrote the literal placeholder rather than the filename. It is a real defect and the number is not tolerable, but the fix belongs to the loader, and blocking the Silver gate on someone else''s bug is how a gate gets switched off. Flip to 0.0 once the loader is fixed.', 'IGNORE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'completeness', 'table_not_empty', 0.0, 'The table holds at least one row', '[structural] Scalar check. An empty table makes every SUM(CASE ...) NULL, and a NULL failed_rows falls through the status CASE to FAIL - loud, but by accident, and reported as dozens of unrelated failures rather than one cause.', 'QUARANTINE', TRUE, 'scalar'),
    ('silver', 'weather_clean', 'validity', 'temperature_parsed', 0.0, 'Temperature survived the conversion from text', '[structural] Bronze weather is entirely text, so this is the try_cast equivalent of a load-fidelity check: a NULL here on a value that was present in Bronze is a conversion we lost. Kept separate from the range checks because out of range and not a number have different fixes.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'temperature_plausible', 5.0, 'Temperature is within a plausible range', '[tolerated] Range assumes the Open-Meteo request used its metric defaults. If it used Fahrenheit this check is wrong and the results still look plausible - worth confirming against the loader once.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'visibility_parsed', 0.0, 'Visibility survived the conversion from text', '[structural] Bronze weather is entirely text, so this is the try_cast equivalent of a load-fidelity check: a NULL here on a value that was present in Bronze is a conversion we lost. Kept separate from the range checks because out of range and not a number have different fixes.', 'QUARANTINE', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'weather_code_parsed', 5.0, 'Weather code survived the conversion from text', '[tolerated] Tolerated source imperfection at the policy threshold. No number here is derived from its own observed rate.', 'FLAG', FALSE, 'table_rows'),
    ('silver', 'weather_clean', 'completeness', 'weather_hour_not_null', 0.0, 'Every weather row has a parsed hour', '[structural] The join key for the entire weather dimension. A null hour cannot match any trip.', 'QUARANTINE', TRUE, 'table_rows'),
    ('silver', 'weather_clean', 'validity', 'wind_speed_parsed', 0.0, 'Wind speed survived the conversion from text', '[structural] Bronze weather is entirely text, so this is the try_cast equivalent of a load-fidelity check: a NULL here on a value that was present in Bronze is a conversion we lost. Kept separate from the range checks because out of range and not a number have different fixes.', 'QUARANTINE', FALSE, 'table_rows')
    AS t(layer, table_name, check_category, check_name, threshold_pct, rule_description, rationale, silver_action, blocking, denominator_scope);

-- ## Results with their severity attached

-- The latest run of each layer, with what each failure actually means.
-- This is the table to put in the write-up.
SELECT
    d.layer, d.table_name, d.check_name,
    d.failed_rows, d.total_rows, d.failed_pct, d.threshold_pct, d.status,
    u.blocking, u.denominator_scope, u.silver_action, u.rule_description,
    CASE WHEN d.status = 'FAIL' AND u.blocking THEN 'BLOCKING FAIL'
         WHEN d.status = 'FAIL'                THEN 'fail (recorded, not blocking)'
         ELSE d.status END                                  AS severity
FROM       `nyc-mobility`.nyc_quality.vw_latest_dq_results d
LEFT JOIN  `nyc-mobility`.nyc_quality.dq_rules             u
       ON  d.layer      = u.layer
      AND  d.table_name = u.table_name
      AND  d.check_name = u.check_name
WHERE  d.status <> 'PASS'
ORDER  BY CASE WHEN d.status = 'FAIL' AND u.blocking THEN 0
               WHEN d.status = 'FAIL'                THEN 1
               ELSE 2 END,
          d.failed_pct DESC;


-- If it ever exists from an older run, it is no longer created or used.
DROP VIEW IF EXISTS `nyc-mobility`.nyc_quality.vw_dq_results_enriched;

-- How many rules, and how many are still guesses

SELECT CASE WHEN rationale LIKE '[structural]%'  THEN 'structural'
            WHEN rationale LIKE '[tolerated]%'   THEN 'tolerated'
            WHEN rationale LIKE '[provisional]%' THEN 'provisional'
            ELSE 'untagged' END                    AS basis,
       COUNT(*)                                    AS rules,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct
FROM   dq_rules
WHERE  layer IN ('bronze', 'silver') AND table_name IN ('green_taxi', 'taxi_zones', 'weather', 'green_taxi_clean', 'taxi_zones_clean', 'weather_clean')
GROUP  BY 1
ORDER  BY rules DESC;


SELECT table_name, check_name, threshold_pct, rule_description
FROM   dq_rules
WHERE  layer IN ('bronze', 'silver') AND table_name IN ('green_taxi', 'taxi_zones', 'weather', 'green_taxi_clean', 'taxi_zones_clean', 'weather_clean')
  AND  rationale LIKE '[provisional]%'
ORDER  BY table_name, check_name;

-- ## 3. Drift guard
--
-- A FULL OUTER JOIN on the check name is the right tool here: it is the
-- one join shape that shows both sides of a mismatch at once — a check
-- that ran with no documented rule, and a rule with no matching check.
-- An inner join would show neither.
--
-- Run it after every change. If both columns are populated on every row,
-- the catalogue and the notebook agree.



-- The latest run OF EACH LAYER. Bronze and Silver are separate notebooks with
-- separate run ids, so there is no single "the latest run" that covers both:
-- MAX(run_ts) across the two always names the Silver one, because Silver runs
-- second. An earlier version resolved one run_id that way and then filtered
-- layer = 'bronze', which asked for Bronze rows carrying a Silver run id --
-- always zero rows, so every rule reported as DOCUMENTED BUT DID NOT RUN.
--
-- GROUP BY layer is what makes it per-layer, and it is the same shape the
-- vw_latest_* views use for the same reason.
WITH latest AS (
    SELECT layer, MAX(run_ts) AS max_ts
    FROM   dq_results
    WHERE  layer IN ('bronze', 'silver')
    GROUP  BY layer
),
ran AS (
    SELECT DISTINCT d.layer, d.table_name, d.check_name, d.threshold_pct
    FROM       dq_results d
    INNER JOIN latest l ON d.layer = l.layer AND d.run_ts = l.max_ts
    WHERE d.table_name IN ('green_taxi', 'taxi_zones', 'weather', 'green_taxi_clean', 'taxi_zones_clean', 'weather_clean')
),
documented AS (
    SELECT layer, table_name, check_name, threshold_pct
    FROM   dq_rules
    WHERE  layer IN ('bronze', 'silver') AND table_name IN ('green_taxi', 'taxi_zones', 'weather', 'green_taxi_clean', 'taxi_zones_clean', 'weather_clean')
)
SELECT
    COALESCE(r.layer, d.layer)                                 AS layer,
    COALESCE(r.table_name, d.table_name)                       AS table_name,
    COALESCE(r.check_name, d.check_name)                       AS check_name,
    r.threshold_pct                                            AS threshold_in_run,
    d.threshold_pct                                            AS threshold_in_rules,
    CASE WHEN d.check_name IS NULL               THEN 'RAN BUT NOT DOCUMENTED'
         WHEN r.check_name IS NULL               THEN 'DOCUMENTED BUT DID NOT RUN'
         WHEN r.threshold_pct <> d.threshold_pct THEN 'THRESHOLD MISMATCH'
         ELSE 'ok' END                                         AS drift
FROM ran r
-- layer is part of the key: the same check_name legitimately exists on both
-- layers (table_not_empty, dq_status_populated, rows_reconcile_with_bronze),
-- and without it those rows cross-join between layers.
FULL OUTER JOIN documented d
  ON  r.layer      = d.layer
  AND r.table_name = d.table_name
  AND r.check_name = d.check_name
WHERE d.check_name IS NULL
   OR r.check_name IS NULL
   OR r.threshold_pct <> d.threshold_pct
ORDER BY drift, layer, table_name, check_name;



-- 4. The catalogue, for the write-up

SELECT table_name, check_category, check_name, threshold_pct,
       blocking, denominator_scope, silver_action, rule_description
FROM   dq_rules
WHERE  layer IN ('bronze', 'silver') AND table_name IN ('green_taxi', 'taxi_zones', 'weather', 'green_taxi_clean', 'taxi_zones_clean', 'weather_clean')
ORDER  BY table_name,
          CASE check_category WHEN 'completeness' THEN 1 WHEN 'uniqueness' THEN 2
               WHEN 'validity' THEN 3 WHEN 'consistency' THEN 4 ELSE 5 END,
          check_name;

-- The reasoning behind every non-default threshold — the rows a reviewer
-- is most likely to challenge.
SELECT table_name, check_name, threshold_pct, rationale
FROM   dq_rules
WHERE  layer IN ('bronze', 'silver') AND table_name IN ('green_taxi', 'taxi_zones', 'weather', 'green_taxi_clean', 'taxi_zones_clean', 'weather_clean')
  AND  threshold_pct NOT IN (5.0)
ORDER  BY threshold_pct, table_name, check_name;

-- Proof that a rerun changes nothing

SELECT version, timestamp, operation,
       operationMetrics['numTargetRowsInserted'] AS inserted,
       operationMetrics['numTargetRowsUpdated']  AS updated,
       operationMetrics['numTargetRowsDeleted']  AS deleted,
       operationMetrics['numTargetRowsCopied']   AS copied
FROM   (DESCRIBE HISTORY dq_rules)
ORDER  BY version DESC
LIMIT  5;