-- dq_rules — the catalogue of every rule, and why each threshold is what it is
-- ## This table is GENERATED, not maintained
--
-- Every row below was extracted from the check notebooks themselves: names,
-- categories, thresholds, row floors and blocking flags are read out of the
-- SQL and the Check() literals, not retyped. Only the two prose columns --
-- rule_description and rationale -- are written by hand.
--
-- That matters because an earlier version of this table documented 118 Bronze
-- rules that no longer existed and none of preload's. A catalogue that drifts
-- from the code is worse than no catalogue: it reads like a guarantee and
-- describes a pipeline nobody is running.
--
-- Section 3 is the guard against that recurring. It compares this table
-- against what dq_results actually emitted, in both directions.
--
-- ## What is in it
--
-- | Layer | Rules | Blocking | Question the layer asks |
-- |---|---|---|---|
-- | preload  | 101 | 17 | is this file fit to load |
-- | bronze   | 42 | 28 | did the loader move it faithfully |
-- | silver   | 87 | 34 | did the transformation classify it correctly |
-- | gold     | 49 | 21 | did the star schema get built from Silver |
-- | at_rest  | 12 | 2 | does the warehouse stand up as it is |
-- | **total**| **291** | **102** | |
--
-- ## Changed in this revision
--
-- Silver retired `out_of_era_pickups_are_quarantined` and gained three
-- promises in its place:
--
--   * out_of_batch_pickups_are_quarantined
--   * out_of_batch_dropoffs_are_quarantined
--   * future_timestamps_are_quarantined
--
-- The old rule tested a hardcoded 2009 literal. Three things were wrong with
-- it: the literal is a fact about this dataset rather than a rule; it was
-- strictly less-than, so exactly 2009-01-01 passed; and it covered PICKUPS
-- only, so a 2026 pickup with a 2009 dropoff passed every rule and still set
-- the dim_date lower bound. The window is now derived per row from
-- `source_file`, and both timestamps are checked.
--
-- The QC check had drifted the same way: it kept PASSing because the new
-- cleaning rules are strictly stronger, so it was green and testing nothing.
--
-- ## Column meanings
--
-- | Column | Holds |
-- |---|---|
-- | `threshold_pct` | the FAIL line: at or under it the check WARNs |
-- | `warn_pct` | the PASS line: at or under it the check is silent |
-- | `min_failed_rows` | absolute floor; at or under it a break is a WARN whatever the rate |
-- | `blocking` | TRUE if a FAIL on this (table, check) pair stops its layer |
-- | `silver_action` | what happens to a row breaking it: QUARANTINE, FLAG, IGNORE, N/A |
-- | `denominator_scope` | what `total_rows` counts, so a percentage can be read |
-- | `rationale` | basis tag, then why this rule and why this threshold |
--
-- Basis tags: `SOURCE_SPEC` (the data dictionary says so) · `PIPELINE_INVARIANT`
-- (our code must hold it) · `BUSINESS_RULE` · `OBSERVED` (tuned from real runs)
-- · `ADVISORY` (recorded, never gates) · `AT_REST` (standing integrity).

-- UTC, pinned, like every other notebook in this project. Nothing here reads a
-- timestamp, but a notebook that sets a different zone from its neighbours is
-- exactly the drift this table exists to catch.
SET TIME ZONE 'UTC';

USE CATALOG nyc_mobility;

-- Full replace. The table is derived, so a partial update is meaningless:
-- either it matches the notebooks or it does not.
TRUNCATE TABLE nyc_quality.dq_rules;

INSERT INTO nyc_quality.dq_rules (
    layer, table_name, check_category, check_name,
    threshold_pct, warn_pct, min_failed_rows, blocking,
    rule_description, rationale, silver_action, denominator_scope
)
VALUES
-- ---------- preload ----------
    ('preload', 'green_taxi', 'validity', 'cast_ok_RatecodeID', 10.0, 5.0, 0, TRUE,
     'Value of RatecodeID is present in the landed file and will not convert to its Bronze type.',
     'PIPELINE_INVARIANT — measured before the write, where the offending value is still visible. Bronze can only report the resulting NULL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'cast_ok_lpep_dropoff_datetime', 10.0, 5.0, 0, TRUE,
     'Value of lpep dropoff datetime is present in the landed file and will not convert to its Bronze type.',
     'PIPELINE_INVARIANT — measured before the write, where the offending value is still visible. Bronze can only report the resulting NULL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'cast_ok_lpep_pickup_datetime', 10.0, 5.0, 0, TRUE,
     'Value of lpep pickup datetime is present in the landed file and will not convert to its Bronze type.',
     'PIPELINE_INVARIANT — measured before the write, where the offending value is still visible. Bronze can only report the resulting NULL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'cast_ok_passenger_count', 10.0, 5.0, 0, TRUE,
     'Value of passenger count is present in the landed file and will not convert to its Bronze type.',
     'PIPELINE_INVARIANT — measured before the write, where the offending value is still visible. Bronze can only report the resulting NULL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'cast_ok_payment_type', 10.0, 5.0, 0, TRUE,
     'Value of payment type is present in the landed file and will not convert to its Bronze type.',
     'PIPELINE_INVARIANT — measured before the write, where the offending value is still visible. Bronze can only report the resulting NULL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'cast_ok_trip_type', 10.0, 5.0, 0, TRUE,
     'Value of trip type is present in the landed file and will not convert to its Bronze type.',
     'PIPELINE_INVARIANT — measured before the write, where the offending value is still visible. Bronze can only report the resulting NULL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'consistency', 'dispatch_fields_null_as_a_set', 0.0, 0.0, 5, FALSE,
     'Dispatch fields are partially populated.',
     'SOURCE_SPEC — they arrive together or not at all.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'consistency', 'dropoff_after_pickup', 10.0, 0.0, 5, FALSE,
     'Dropoff timestamp precedes pickup, measured on the landed file.',
     'BUSINESS_RULE — same rule, one layer earlier.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'dropoff_datetime_not_null', 0.0, 0.0, 5, FALSE,
     'Column dropoff datetime is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'dropoff_zone_in_range', 10.0, 0.0, 5, FALSE,
     'Value of dropoff zone is outside its valid bounds.',
     'SOURCE_SPEC — out-of-range values do not join and would silently drop.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'dropoff_zone_not_null', 0.0, 0.0, 5, FALSE,
     'Column dropoff zone is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'green_taxi', 'consistency', 'duration_not_zero', 10.0, 0.0, 5, FALSE,
     'Pickup and dropoff are the same instant.',
     'BUSINESS_RULE — a zero-length trip is a cancellation.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'consistency', 'duration_under_24_hours', 10.0, 0.0, 5, FALSE,
     'Trip duration exceeds 24 hours.',
     'OBSERVED — a meter left running, not a trip.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'schema', 'expected_columns_present', 0.0, 0.0, 0, TRUE,
     'A column the declared schema names is missing from the file.',
     'PIPELINE_INVARIANT — read_files() with a declared schema maps CSV BY POSITION. This compares as a set, so it catches a rename but NOT a reorder. Known gap.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'expected_file_present', 0.0, 0.0, 0, TRUE,
     'The file this batch needs is not in the landing volume.',
     'PIPELINE_INVARIANT — nothing downstream can proceed without it, and the failure is cheapest to report here.', 'FLAG', 'scalar (1)'),
    ('preload', 'green_taxi', 'validity', 'fare_amount_not_negative', 10.0, 0.0, 5, FALSE,
     'fare_amount is below zero.',
     'BUSINESS_RULE — a refund, not a trip.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'fare_amount_not_null', 10.0, 0.0, 5, FALSE,
     'Column fare amount is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'business', 'fare_implies_some_distance', 10.0, 0.0, 5, FALSE,
     'A non-trivial fare with zero distance.',
     'OBSERVED — a fare with no distance is a cancelled or mis-metered trip.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'business', 'fare_plausible_for_duration', 10.0, 0.0, 5, FALSE,
     'Fare is implausible for the trip duration.',
     'OBSERVED — catches meter faults and unit mix-ups.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'file_not_empty', 0.0, 0.0, 0, TRUE,
     'The landed file has zero rows.',
     'PIPELINE_INVARIANT — a zero-byte download looks like a successful ingestion.', 'FLAG', 'scalar (1)'),
    ('preload', 'green_taxi', 'business', 'implied_speed_under_100mph', 10.0, 0.0, 5, FALSE,
     'Distance over duration exceeds 100 mph.',
     'OBSERVED — physically impossible; indicates a bad timestamp or distance.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'consistency', 'myle_dispatch_fields_stay_null', 0.0, 0.0, 5, FALSE,
     'Vendor 6 rows populate the dispatch fields.',
     'SOURCE_SPEC — Myle never populates them; a value means the vendor mapping changed.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'business', 'myle_fare_stays_placeholder', 0.0, 0.0, 5, FALSE,
     'A vendor 6 fare departs from its placeholder value.',
     'SOURCE_SPEC — Myle reports a fixed placeholder, not a real fare.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'uniqueness', 'no_exact_duplicate_rows', 10.0, 0.0, 5, FALSE,
     'Byte-identical duplicate rows in the landed file.',
     'OBSERVED — a re-download appended rather than replaced. Tolerated: the MERGE deduplicates, so this is information about the file, not a reason to refuse it.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'no_fractional_loss_RatecodeID', 10.0, 5.0, 0, TRUE,
     'Value of RatecodeID converts to INT but changes — 2.7 becomes 2.',
     'PIPELINE_INVARIANT — CAST truncates silently under ANSI mode: no error, no NULL. The only check in the pipeline that can see this, and it must run before the write.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'no_fractional_loss_passenger_count', 10.0, 5.0, 0, TRUE,
     'Value of passenger count converts to INT but changes — 2.7 becomes 2.',
     'PIPELINE_INVARIANT — CAST truncates silently under ANSI mode: no error, no NULL. The only check in the pipeline that can see this, and it must run before the write.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'no_fractional_loss_payment_type', 10.0, 5.0, 0, TRUE,
     'Value of payment type converts to INT but changes — 2.7 becomes 2.',
     'PIPELINE_INVARIANT — CAST truncates silently under ANSI mode: no error, no NULL. The only check in the pipeline that can see this, and it must run before the write.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'no_fractional_loss_trip_type', 10.0, 5.0, 0, TRUE,
     'Value of trip type converts to INT but changes — 2.7 becomes 2.',
     'PIPELINE_INVARIANT — CAST truncates silently under ANSI mode: no error, no NULL. The only check in the pipeline that can see this, and it must run before the write.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'business', 'no_tip_recorded_on_cash', 10.0, 0.0, 5, FALSE,
     'A cash trip records a tip.',
     'BUSINESS_RULE — same rule, measured on the landed file.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'schema', 'no_unexpected_columns', 100.0, 0.0, 0, FALSE,
     'The file carries a column the schema does not name.',
     'ADVISORY — a new upstream column is information, not a defect, but it is how a positional mapping silently shifts.', 'IGNORE', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'passenger_count_not_negative', 0.0, 0.0, 5, FALSE,
     'passenger_count is below zero.',
     'BUSINESS_RULE — a negative count is a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'passenger_count_not_null_excl_myle', 10.0, 0.0, 5, FALSE,
     'passenger_count is NULL on a non-Myle row.',
     'SOURCE_SPEC — vendor 6 never populates it, so counting its rows reports a structural absence as missing data.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'passenger_count_not_zero', 10.0, 0.0, 5, FALSE,
     'passenger_count is zero.',
     'BUSINESS_RULE — a trip with no passengers is a deadhead or a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'passenger_count_plausible', 10.0, 0.0, 5, FALSE,
     'passenger_count exceeds vehicle capacity.',
     'SOURCE_SPEC — a green taxi seats at most a handful.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'payment_type_in_domain', 10.0, 0.0, 5, FALSE,
     'Value of payment type is outside the set the data dictionary defines.',
     'SOURCE_SPEC — TLC publishes the code list; a value outside it is a source change or a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'pickup_datetime_not_null', 0.0, 0.0, 5, FALSE,
     'Column pickup datetime is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'pickup_month_matches_source_file', 10.0, 0.0, 5, FALSE,
     'A trip pickup month differs from the file month.',
     'SOURCE_SPEC — TLC files reliably carry a few out-of-month trips; tolerated, recorded.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'pickup_zone_in_range', 10.0, 0.0, 5, FALSE,
     'Value of pickup zone is outside its valid bounds.',
     'SOURCE_SPEC — out-of-range values do not join and would silently drop.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'pickup_zone_not_null', 0.0, 0.0, 5, FALSE,
     'Column pickup zone is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'ratecode_in_domain', 10.0, 0.0, 5, FALSE,
     'Value of ratecode is outside the set the data dictionary defines.',
     'SOURCE_SPEC — TLC publishes the code list; a value outside it is a source change or a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'store_and_fwd_flag_in_domain', 10.0, 0.0, 5, FALSE,
     'Value of store and fwd flag is outside the set the data dictionary defines.',
     'SOURCE_SPEC — TLC publishes the code list; a value outside it is a source change or a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'total_amount_not_negative', 10.0, 0.0, 5, FALSE,
     'total_amount is below zero.',
     'BUSINESS_RULE — a refund, not a trip.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'total_amount_not_null', 10.0, 0.0, 5, FALSE,
     'Column total amount is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'business', 'total_equals_sum_of_charges_v1', 10.0, 0.0, 5, FALSE,
     'Vendor 1 total_amount does not equal its charge components.',
     'BUSINESS_RULE — vendor 1 EXCLUDES the three surcharges. Applying vendor 2 eight-term formula to both produced a 10.63% false FAIL.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'business', 'total_equals_sum_of_charges_v2', 10.0, 0.0, 5, FALSE,
     'Vendor 2 total_amount does not equal its eight charge components.',
     'BUSINESS_RULE — vendor 2 includes improvement, congestion and CBD surcharges.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'trip_distance_not_negative', 0.0, 0.0, 5, FALSE,
     'trip_distance is below zero.',
     'BUSINESS_RULE — a negative distance is a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'trip_distance_not_null', 10.0, 0.0, 5, FALSE,
     'Column trip distance is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'trip_distance_plausible', 10.0, 0.0, 5, FALSE,
     'trip_distance exceeds a plausible maximum.',
     'OBSERVED — a runaway odometer value.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'trip_type_in_domain', 10.0, 0.0, 5, FALSE,
     'Value of trip type is outside the set the data dictionary defines.',
     'SOURCE_SPEC — TLC publishes the code list; a value outside it is a source change or a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'validity', 'vendor_id_in_domain', 10.0, 0.0, 5, FALSE,
     'Value of vendor id is outside the set the data dictionary defines.',
     'SOURCE_SPEC — TLC publishes the code list; a value outside it is a source change or a bad row.', 'FLAG', 'rows in the landed file'),
    ('preload', 'green_taxi', 'completeness', 'vendor_id_not_null', 10.0, 0.0, 5, FALSE,
     'Column vendor id is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'business', 'airport_zones_present', 0.0, 0.0, 0, FALSE,
     'The JFK, LaGuardia and Newark zones are missing.',
     'BUSINESS_RULE — airport trips are a headline segment; their absence means a bad copy.', 'FLAG', 'scalar (1)'),
    ('preload', 'taxi_zones', 'validity', 'borough_in_domain', 10.0, 0.0, 5, FALSE,
     'borough is outside the five boroughs plus Unknown/EWR.',
     'SOURCE_SPEC — TLC publishes the list.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'completeness', 'borough_not_null', 10.0, 0.0, 5, FALSE,
     'borough is NULL in the landed lookup.',
     'SOURCE_SPEC — required for the borough breakdown.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'schema', 'expected_columns_present', 0.0, 0.0, 0, FALSE,
     'A column the declared schema names is missing from the file.',
     'PIPELINE_INVARIANT — read_files() with a declared schema maps CSV BY POSITION. This compares as a set, so it catches a rename but NOT a reorder. Known gap.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'completeness', 'expected_file_present', 0.0, 0.0, 0, FALSE,
     'The file this batch needs is not in the landing volume.',
     'PIPELINE_INVARIANT — nothing downstream can proceed without it, and the failure is cheapest to report here.', 'FLAG', 'scalar (1)'),
    ('preload', 'taxi_zones', 'completeness', 'file_not_empty', 0.0, 0.0, 0, FALSE,
     'The landed file has zero rows.',
     'PIPELINE_INVARIANT — a zero-byte download looks like a successful ingestion.', 'FLAG', 'scalar (1)'),
    ('preload', 'taxi_zones', 'validity', 'location_id_in_range', 10.0, 0.0, 5, FALSE,
     'location_id is outside 1-265.',
     'SOURCE_SPEC — the published id range.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'completeness', 'location_id_not_null', 0.0, 0.0, 0, TRUE,
     'Column location id is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'uniqueness', 'location_id_unique', 0.0, 0.0, 0, TRUE,
     'Duplicate location_id in the lookup.',
     'PIPELINE_INVARIANT — the lookup is a primary key or it is nothing. No row floor.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'business', 'lookup_has_265_zones', 0.0, 0.0, 0, FALSE,
     'The zone lookup does not hold exactly 265 rows.',
     'SOURCE_SPEC — TLC publishes 265 zones. A different number is a source change.', 'FLAG', 'scalar (1)'),
    ('preload', 'taxi_zones', 'schema', 'no_unexpected_columns', 100.0, 0.0, 0, FALSE,
     'The file carries a column the schema does not name.',
     'ADVISORY — a new upstream column is information, not a defect, but it is how a positional mapping silently shifts.', 'IGNORE', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'validity', 'service_zone_in_domain', 10.0, 0.0, 5, FALSE,
     'service_zone is outside the published set.',
     'SOURCE_SPEC — TLC publishes the list.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'completeness', 'service_zone_not_null', 10.0, 0.0, 5, FALSE,
     'service_zone is NULL in the landed lookup.',
     'SOURCE_SPEC — required for the service-zone breakdown.', 'FLAG', 'rows in the landed file'),
    ('preload', 'taxi_zones', 'completeness', 'zone_name_not_null', 10.0, 0.0, 5, FALSE,
     'zone_name is NULL in the landed lookup.',
     'SOURCE_SPEC — required for the zone label.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'apparent_temp_not_null', 10.0, 0.0, 5, FALSE,
     'Column apparent temp is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'apparent_temp_parses', 10.0, 5.0, 5, FALSE,
     'Value of apparent temp is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'cloud_cover_0_to_100', 10.0, 0.0, 5, FALSE,
     'Cloud cover is outside 0-100.',
     'SOURCE_SPEC — it is a percentage.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'cloud_cover_not_null', 10.0, 0.0, 5, FALSE,
     'Column cloud cover is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'cloud_cover_parses', 10.0, 5.0, 5, FALSE,
     'Value of cloud cover is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'date_not_null', 0.0, 0.0, 0, TRUE,
     'The date column is NULL in the landed weather file.',
     'PIPELINE_INVARIANT — it is the MERGE key. Blocking at preload: nothing downstream can key on it.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'date_parses', 0.0, 0.0, 0, TRUE,
     'The date column is present and will not convert to TIMESTAMP.',
     'PIPELINE_INVARIANT — an unparseable key is the same defect as a missing one.', 'QUARANTINE', 'rows in the landed file'),
    ('preload', 'weather', 'schema', 'expected_columns_present', 0.0, 0.0, 0, FALSE,
     'A column the declared schema names is missing from the file.',
     'PIPELINE_INVARIANT — read_files() with a declared schema maps CSV BY POSITION. This compares as a set, so it catches a rename but NOT a reorder. Known gap.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'expected_file_present', 0.0, 0.0, 0, FALSE,
     'The file this batch needs is not in the landing volume.',
     'PIPELINE_INVARIANT — nothing downstream can proceed without it, and the failure is cheapest to report here.', 'FLAG', 'scalar (1)'),
    ('preload', 'weather', 'completeness', 'file_not_empty', 0.0, 0.0, 0, FALSE,
     'The landed file has zero rows.',
     'PIPELINE_INVARIANT — a zero-byte download looks like a successful ingestion.', 'FLAG', 'scalar (1)'),
    ('preload', 'weather', 'consistency', 'gusts_at_least_wind_speed', 10.0, 0.0, 5, FALSE,
     'Wind gust is below sustained wind speed.',
     'SOURCE_SPEC — physically impossible; a gust is a peak.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'hour_within_batch_month', 100.0, 0.0, 5, FALSE,
     'An hour in the file falls outside the batch month.',
     'ADVISORY — same UTC boundary spill, measured on the raw file.', 'IGNORE', 'rows in the landed file'),
    ('preload', 'weather', 'consistency', 'month_agrees_with_date', 10.0, 0.0, 5, FALSE,
     'The month column disagrees with the date column.',
     'ADVISORY — same cause as the boundary spill.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'month_not_null', 10.0, 0.0, 5, FALSE,
     'The month column is NULL in the landed weather file.',
     'SOURCE_SPEC — used to confirm the file is the month it claims.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'schema', 'no_unexpected_columns', 100.0, 0.0, 0, FALSE,
     'The file carries a column the schema does not name.',
     'ADVISORY — a new upstream column is information, not a defect, but it is how a positional mapping silently shifts.', 'IGNORE', 'rows in the landed file'),
    ('preload', 'weather', 'uniqueness', 'one_row_per_hour', 100.0, 0.0, 0, FALSE,
     'More than one row for the same hour.',
     'PIPELINE_INVARIANT — the hour is the MERGE key. No row floor: one duplicate is the defect.', 'IGNORE', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'precip_probability_0_to_100', 10.0, 0.0, 5, FALSE,
     'Precipitation probability is outside 0-100.',
     'SOURCE_SPEC — it is a percentage.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'precip_probability_not_null', 10.0, 0.0, 5, FALSE,
     'Column precip probability is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'precip_probability_parses', 10.0, 5.0, 5, FALSE,
     'Value of precip probability is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'rain_not_negative', 10.0, 0.0, 5, FALSE,
     'Rain is below zero.',
     'SOURCE_SPEC — physically impossible.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'rain_not_null', 10.0, 0.0, 5, FALSE,
     'Column rain is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'rain_parses', 10.0, 5.0, 5, FALSE,
     'Value of rain is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'temperature_not_null', 10.0, 0.0, 5, FALSE,
     'Column temperature is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'temperature_parses', 10.0, 5.0, 5, FALSE,
     'Value of temperature is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'temperature_plausible', 10.0, 0.0, 5, FALSE,
     'Temperature is outside a plausible range for New York.',
     'OBSERVED — catches a unit swap between C and F.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'visibility_not_negative', 10.0, 0.0, 5, FALSE,
     'Visibility is below zero.',
     'SOURCE_SPEC — physically impossible.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'visibility_not_null', 10.0, 0.0, 5, FALSE,
     'Column visibility is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'visibility_parses', 10.0, 5.0, 5, FALSE,
     'Value of visibility is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'weather_code_in_wmo_domain', 10.0, 0.0, 5, FALSE,
     'weather_code is outside the WMO code list.',
     'SOURCE_SPEC — Open-Meteo publishes the WMO codes it emits.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'weather_code_not_null', 10.0, 0.0, 5, FALSE,
     'Column weather code is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'weather_code_parses', 10.0, 5.0, 5, FALSE,
     'Value of weather code is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'wind_gusts_not_null', 10.0, 0.0, 5, FALSE,
     'Column wind gusts is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'wind_gusts_parses', 10.0, 5.0, 5, FALSE,
     'Value of wind gusts is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'wind_speed_not_negative', 10.0, 0.0, 5, FALSE,
     'Wind speed is below zero.',
     'SOURCE_SPEC — physically impossible.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'completeness', 'wind_speed_not_null', 10.0, 0.0, 5, FALSE,
     'Column wind speed is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'FLAG', 'rows in the landed file'),
    ('preload', 'weather', 'validity', 'wind_speed_parses', 10.0, 5.0, 5, FALSE,
     'Value of wind speed is present in the source text and does not convert to DOUBLE.',
     'SOURCE_SPEC — the feed is text. A value that will not parse is a real loss; a value the feed never sent is not. 5/10 pairs warn and fail.', 'FLAG', 'rows in the landed file'),
-- ---------- bronze ----------
    ('bronze', 'green_taxi', 'consistency', 'dropoff_zone_exists_in_lookup', 0.0, 0.0, 5, FALSE,
     'A dropoff zone id has no row in the lookup.',
     'PIPELINE_INVARIANT — the join Gold depends on.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'business', 'every_landed_file_is_loaded', 0.0, 0.0, 5, TRUE,
     'A file present in the volume has no rows in the table.',
     'PIPELINE_INVARIANT — a skipped file is invisible to every row-level check.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'ingestion_time_recorded', 10.0, 0.0, 5, FALSE,
     'Lineage column ingestion_time is NULL.',
     'PIPELINE_INVARIANT — the dedup ORDER BY depends on it.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_congestion_surcharge', 0.0, 0.0, 5, TRUE,
     'Column congestion surcharge is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_do_location_id', 0.0, 0.0, 5, TRUE,
     'Column do location id is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_dropoff_datetime', 0.0, 0.0, 5, TRUE,
     'Column dropoff datetime is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_extra', 0.0, 0.0, 5, TRUE,
     'Column extra is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_fare_amount', 0.0, 0.0, 5, TRUE,
     'Column fare amount is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_improvement_surcharge', 0.0, 0.0, 5, TRUE,
     'Column improvement surcharge is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_mta_tax', 0.0, 0.0, 5, TRUE,
     'Column mta tax is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_passenger_count', 0.0, 0.0, 5, TRUE,
     'Column passenger count is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_payment_type', 0.0, 0.0, 5, TRUE,
     'Column payment type is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_pickup_datetime', 0.0, 0.0, 5, TRUE,
     'Column pickup datetime is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_pu_location_id', 0.0, 0.0, 5, TRUE,
     'Column pu location id is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_ratecode_id', 0.0, 0.0, 5, TRUE,
     'Column ratecode id is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_store_and_fwd_flag', 0.0, 0.0, 5, TRUE,
     'Column store and fwd flag is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_tip_amount', 0.0, 0.0, 5, TRUE,
     'Column tip amount is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_tolls_amount', 0.0, 0.0, 5, TRUE,
     'Column tolls amount is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_total_amount', 0.0, 0.0, 5, TRUE,
     'Column total amount is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_trip_distance', 0.0, 0.0, 5, TRUE,
     'Column trip distance is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_trip_type', 0.0, 0.0, 5, TRUE,
     'Column trip type is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'no_nulls_added_vendor_id', 0.0, 0.0, 5, TRUE,
     'Column vendor id is populated in the source file and NULL in the table for the same batch.',
     'PIPELINE_INVARIANT — the MERGE casts this column. A value the source had and the table does not is a cast that failed, not a source gap. 5/10 because a source that is a few percent unparseable is a known condition, not a broken load.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'consistency', 'pickup_zone_exists_in_lookup', 0.0, 0.0, 5, FALSE,
     'A pickup zone id has no row in the lookup.',
     'PIPELINE_INVARIANT — the join Gold depends on, tested before Gold is built.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'business', 'row_count_matches_source', 0.0, 0.0, 5, TRUE,
     'Rows in the table for this batch differ from rows in the file.',
     'PIPELINE_INVARIANT — not recoverable by re-running: the MERGE matches on source_file, so a partial load stays partial.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'source_file_recorded', 0.0, 0.0, 5, FALSE,
     'Lineage column source_file is NULL.',
     'PIPELINE_INVARIANT — without it a row cannot be traced to a file and cannot be re-loaded.', 'FLAG', 'rows in the batch'),
    ('bronze', 'green_taxi', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'FLAG', 'scalar (1)'),
    ('bronze', 'green_taxi', 'consistency', 'trips_with_unmatched_dropoff_zone', 100.0, 0.0, 5, FALSE,
     'Trips whose dropoff zone does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'IGNORE', 'rows in the batch'),
    ('bronze', 'green_taxi', 'consistency', 'trips_with_unmatched_pickup_zone', 100.0, 0.0, 5, FALSE,
     'Trips whose pickup zone does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'IGNORE', 'rows in the batch'),
    ('bronze', 'taxi_zones', 'completeness', 'ingestion_time_recorded', 10.0, 0.0, 5, FALSE,
     'Lineage column ingestion_time is NULL.',
     'PIPELINE_INVARIANT — the dedup ORDER BY depends on it.', 'FLAG', 'rows in the batch'),
    ('bronze', 'taxi_zones', 'uniqueness', 'location_id_unique', 0.0, 0.0, 0, TRUE,
     'Duplicate location_id in the lookup.',
     'PIPELINE_INVARIANT — the lookup is a primary key or it is nothing. No row floor.', 'FLAG', 'rows in the batch'),
    ('bronze', 'taxi_zones', 'completeness', 'source_file_recorded', 0.0, 0.0, 5, FALSE,
     'Lineage column source_file is NULL.',
     'PIPELINE_INVARIANT — without it a row cannot be traced to a file and cannot be re-loaded.', 'FLAG', 'rows in the batch'),
    ('bronze', 'taxi_zones', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'FLAG', 'scalar (1)'),
    ('bronze', 'taxi_zones', 'business', 'zone_names_shared_is_3', 100.0, 0.0, 5, FALSE,
     'The count of zone names shared across boroughs is not 3.',
     'SOURCE_SPEC — TLC reuses three names across boroughs. A different count means the lookup changed shape.', 'IGNORE', 'scalar (1)'),
    ('bronze', 'weather', 'business', 'every_landed_file_is_loaded', 0.0, 0.0, 5, TRUE,
     'A file present in the volume has no rows in the table.',
     'PIPELINE_INVARIANT — a skipped file is invisible to every row-level check.', 'FLAG', 'rows in the batch'),
    ('bronze', 'weather', 'validity', 'hour_within_covered_months', 100.0, 0.0, 5, FALSE,
     'An hour falls outside the months this table covers.',
     'ADVISORY — the weather feed is UTC and the project is New York, so boundary hours legitimately land either side. Worth seeing, not gating on.', 'IGNORE', 'rows in the batch'),
    ('bronze', 'weather', 'completeness', 'ingestion_time_recorded', 10.0, 0.0, 5, FALSE,
     'Lineage column ingestion_time is NULL.',
     'PIPELINE_INVARIANT — the dedup ORDER BY depends on it.', 'FLAG', 'rows in the batch'),
    ('bronze', 'weather', 'uniqueness', 'one_row_per_hour', 0.0, 0.0, 0, TRUE,
     'More than one row for the same hour.',
     'PIPELINE_INVARIANT — the hour is the MERGE key. No row floor: one duplicate is the defect.', 'FLAG', 'rows in the batch'),
    ('bronze', 'weather', 'business', 'row_count_matches_source', 0.0, 0.0, 5, TRUE,
     'Rows in the table for this batch differ from rows in the file.',
     'PIPELINE_INVARIANT — not recoverable by re-running: the MERGE matches on source_file, so a partial load stays partial.', 'FLAG', 'rows in the batch'),
    ('bronze', 'weather', 'consistency', 'source_file_is_not_placeholder', 100.0, 0.0, 5, FALSE,
     'source_file holds the literal parameter name.',
     'PIPELINE_INVARIANT — happens when the notebook runs as plain SQL rather than through parameter substitution. Lineage is gone and nothing else notices.', 'IGNORE', 'scalar (1)'),
    ('bronze', 'weather', 'completeness', 'source_file_recorded', 0.0, 0.0, 5, FALSE,
     'Lineage column source_file is NULL.',
     'PIPELINE_INVARIANT — without it a row cannot be traced to a file and cannot be re-loaded.', 'FLAG', 'rows in the batch'),
    ('bronze', 'weather', 'uniqueness', 'source_rows_deduplicated', 100.0, 0.0, 5, FALSE,
     'Duplicate source rows survived the MERGE.',
     'PIPELINE_INVARIANT — a duplicated key fans out through every downstream join.', 'IGNORE', 'rows in the batch'),
    ('bronze', 'weather', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'FLAG', 'scalar (1)'),
-- ---------- silver ----------
    ('silver', 'green_taxi_clean', 'validity', 'cash_trips_carry_no_tip', 0.0, 0.0, 5, FALSE,
     'A cash trip records a tip.',
     'BUSINESS_RULE — TLC does not capture cash tips; a value here is a data entry artefact.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'validity', 'coalesced_codes_not_null', 0.0, 0.0, 5, FALSE,
     'A code Silver coalesces is still NULL.',
     'PIPELINE_INVARIANT — asserts the COALESCE ran.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'dedup_removal_rate', 10.0, 0.0, 5, FALSE,
     'Share of Bronze rows removed by Silver deduplication.',
     'ADVISORY — a number that climbs run over run means the key is getting coarser.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'validity', 'dq_status_in_domain', 0.0, 0.0, 5, TRUE,
     'dq_status holds a value outside PASS/WARN/FAIL.',
     'PIPELINE_INVARIANT — a fourth value silently escapes every downstream filter.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'completeness', 'dq_status_populated', 0.0, 0.0, 5, TRUE,
     'dq_status is NULL.',
     'PIPELINE_INVARIANT — Gold filters on it; a NULL classifies as nothing.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'dropoff_zone_exists_in_lookup', 0.0, 0.0, 5, FALSE,
     'A dropoff zone id has no row in the lookup.',
     'PIPELINE_INVARIANT — the join Gold depends on.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'every_bronze_file_present', 0.0, 0.0, 5, TRUE,
     'A source file in Bronze has no rows in Silver.',
     'PIPELINE_INVARIANT — a dropped file passes every row-level check.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'fail_rows_carry_a_fail_issue', 0.0, 0.0, 5, TRUE,
     'A FAIL row names no FAIL: issue.',
     'PIPELINE_INVARIANT — the row is quarantined with no stated reason.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'future_timestamps_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A pickup or dropoff after the current time did not receive the FAIL label.',
     'PIPELINE_INVARIANT — the backstop for a row whose source_file is unparseable, so the window rules have nothing to work with. Needs no literal: no trip can be in the future, in any dataset.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'completeness', 'ingestion_time_recorded', 10.0, 0.0, 5, FALSE,
     'Lineage column ingestion_time is NULL.',
     'PIPELINE_INVARIANT — the dedup ORDER BY depends on it.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'null_timestamps_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A row meeting the null timestamps condition did not receive the FAIL label.',
     'PIPELINE_INVARIANT — this can only fail if the classification CASE is wrong. Gold filters on dq_status, so a row that escaped the label is in Gold being counted.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'uniqueness', 'one_row_per_merge_key', 0.0, 0.0, 5, TRUE,
     'More than one row for the same merge key in the target.',
     'PIPELINE_INVARIANT — the MERGE would update the same row twice per run.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'out_of_batch_dropoffs_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A dropoff more than a month outside its own source file month did not receive the FAIL label.',
     'PIPELINE_INVARIANT — the dropoff had no era rule at all. A 2026 pickup with a 2009 dropoff passed every rule and still set the dim_date lower bound, producing a 6,301-day calendar.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'out_of_batch_pickups_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A pickup more than a month outside its own source file month did not receive the FAIL label.',
     'PIPELINE_INVARIANT — the window is derived per row from source_file, not a hardcoded era. Replaced out_of_era_pickups_are_quarantined, which tested pickup < 2009-01-01: a literal the cleaning notebook had stopped using, so the check stayed green while testing nothing.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'pass_rows_carry_no_issues', 0.0, 0.0, 5, TRUE,
     'A PASS row has a non-empty issue array.',
     'PIPELINE_INVARIANT — can only fail if the classification CASE is wrong.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'validity', 'passenger_count_at_least_one', 0.0, 0.0, 5, FALSE,
     'passenger_count is below one after cleaning.',
     'PIPELINE_INVARIANT — Silver clamps; this asserts the clamp ran.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'pickup_zone_exists_in_lookup', 0.0, 0.0, 5, FALSE,
     'A pickup zone id has no row in the lookup.',
     'PIPELINE_INVARIANT — the join Gold depends on, tested before Gold is built.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'completeness', 'qc_array_not_null', 0.0, 0.0, 5, TRUE,
     'qc_error_descriptions is NULL rather than an empty array.',
     'PIPELINE_INVARIANT — NULL and empty behave differently in exists() and size().', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'validity', 'qc_entries_carry_severity_prefix', 0.0, 0.0, 5, TRUE,
     'An issue entry starts with neither FAIL: nor WARN:.',
     'PIPELINE_INVARIANT — a forgotten prefix silently downgrades a FAIL row to WARN. Seven characters, invisible without this check.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'business', 'quarantine_rate_within_limit', 10.0, 0.0, 5, FALSE,
     'Share of rows Silver classified FAIL.',
     'OBSERVED — a rate that jumps between batches is a source change, not a bad batch.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'revenue_preserved', 0.0, 0.0, 5, TRUE,
     'Total revenue differs between layers beyond 0.1% or $1.',
     'PIPELINE_INVARIANT — a row count can match while values shift. Money is the check that notices.', 'FLAG', 'scalar (1)'),
    ('silver', 'green_taxi_clean', 'consistency', 'reversed_trips_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A row meeting the reversed trips condition did not receive the FAIL label.',
     'PIPELINE_INVARIANT — this can only fail if the classification CASE is wrong. Gold filters on dq_status, so a row that escaped the label is in Gold being counted.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'business', 'rows_carrying_a_warning', 100.0, 0.0, 5, FALSE,
     'Share of rows carrying at least one WARN issue.',
     'ADVISORY — a level to watch, not a threshold to pass.', 'IGNORE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'rows_reconcile_with_bronze', 0.0, 0.0, 5, TRUE,
     'Silver row count differs from deduplicated Bronze.',
     'PIPELINE_INVARIANT — computed with Silver OWN key, nulling out-of-range ids before partitioning, so it measures the transform rather than the dedup.', 'FLAG', 'scalar (1)'),
    ('silver', 'green_taxi_clean', 'completeness', 'silver_at_recorded', 0.0, 0.0, 5, TRUE,
     'Lineage column silver_at is NULL.',
     'PIPELINE_INVARIANT — records when the row was last cleaned.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'business', 'silver_retention_rate', 100.0, 0.0, 5, FALSE,
     'Share of Bronze rows that survived into Silver.',
     'ADVISORY — the headline number for a batch.', 'IGNORE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'completeness', 'source_file_recorded', 0.0, 0.0, 5, TRUE,
     'Lineage column source_file is NULL.',
     'PIPELINE_INVARIANT — without it a row cannot be traced to a file and cannot be re-loaded.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'validity', 'surcharges_not_negative', 0.0, 0.0, 5, FALSE,
     'A surcharge is negative after cleaning.',
     'PIPELINE_INVARIANT — Silver clamps to zero; this asserts the clamp ran.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'FLAG', 'scalar (1)'),
    ('silver', 'green_taxi_clean', 'business', 'total_equals_sum_of_charges_v1', 10.0, 0.0, 5, FALSE,
     'Vendor 1 total_amount does not equal its charge components.',
     'BUSINESS_RULE — vendor 1 EXCLUDES the three surcharges. Applying vendor 2 eight-term formula to both produced a 10.63% false FAIL.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'business', 'total_equals_sum_of_charges_v2', 10.0, 0.0, 5, FALSE,
     'Vendor 2 total_amount does not equal its eight charge components.',
     'BUSINESS_RULE — vendor 2 includes improvement, congestion and CBD surcharges.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'trip_hour_has_weather', 10.0, 0.0, 5, FALSE,
     'A trip hour in this batch has no weather row.',
     'PIPELINE_INVARIANT — the join Gold depends on, tested before Gold is built.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'trip_hour_has_weather_any_batch', 100.0, 0.0, 5, FALSE,
     'A trip hour has no weather row in ANY batch.',
     'ADVISORY — the twin of the above. Equal counts prove the hours are genuinely missing rather than spilling across a batch boundary.', 'IGNORE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'trips_with_unmatched_dropoff_zone', 100.0, 0.0, 5, FALSE,
     'Trips whose dropoff zone does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'IGNORE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'trips_with_unmatched_pickup_zone', 100.0, 0.0, 5, FALSE,
     'Trips whose pickup zone does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'IGNORE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'unresolvable_zones_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A row meeting the unresolvable zones condition did not receive the FAIL label.',
     'PIPELINE_INVARIANT — this can only fail if the classification CASE is wrong. Gold filters on dq_status, so a row that escaped the label is in Gold being counted.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'untraceable_rows_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A row with no usable lineage is not labelled FAIL.',
     'PIPELINE_INVARIANT — an untraceable row cannot be re-loaded or explained.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'consistency', 'warn_rows_carry_only_warn_issues', 0.0, 0.0, 5, TRUE,
     'A WARN row carries a FAIL: issue, or none at all.',
     'PIPELINE_INVARIANT — a mislabelled row is in Gold being counted.', 'FLAG', 'rows in the batch'),
    ('silver', 'green_taxi_clean', 'validity', 'zones_within_1_to_265', 0.0, 0.0, 5, FALSE,
     'A location id outside 1-265 survived cleaning.',
     'PIPELINE_INVARIANT — Silver nulls them; this asserts it did.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'business', 'airport_zones_present', 0.0, 0.0, 5, FALSE,
     'The JFK, LaGuardia and Newark zones are missing.',
     'BUSINESS_RULE — airport trips are a headline segment; their absence means a bad copy.', 'FLAG', 'scalar (1)'),
    ('silver', 'taxi_zones_clean', 'validity', 'borough_in_domain', 10.0, 0.0, 5, FALSE,
     'borough is outside the five boroughs plus Unknown/EWR.',
     'SOURCE_SPEC — TLC publishes the list.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'completeness', 'borough_not_blank', 0.0, 0.0, 5, FALSE,
     'Column borough is NULL or trims to an empty string.',
     'SOURCE_SPEC — a blank label reads as a real category in a group-by.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'validity', 'location_id_in_range', 0.0, 0.0, 5, FALSE,
     'location_id is outside 1-265.',
     'SOURCE_SPEC — the published id range.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'completeness', 'location_id_not_null', 0.0, 0.0, 0, TRUE,
     'Column location id is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'uniqueness', 'location_id_unique', 0.0, 0.0, 0, TRUE,
     'Duplicate location_id in the lookup.',
     'PIPELINE_INVARIANT — the lookup is a primary key or it is nothing. No row floor.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'business', 'lookup_has_265_zones', 0.0, 0.0, 5, FALSE,
     'The zone lookup does not hold exactly 265 rows.',
     'SOURCE_SPEC — TLC publishes 265 zones. A different number is a source change.', 'FLAG', 'scalar (1)'),
    ('silver', 'taxi_zones_clean', 'consistency', 'rows_reconcile_with_bronze', 0.0, 0.0, 5, FALSE,
     'Silver row count differs from deduplicated Bronze.',
     'PIPELINE_INVARIANT — computed with Silver OWN key, nulling out-of-range ids before partitioning, so it measures the transform rather than the dedup.', 'FLAG', 'scalar (1)'),
    ('silver', 'taxi_zones_clean', 'validity', 'service_zone_in_domain', 10.0, 0.0, 5, FALSE,
     'service_zone is outside the published set.',
     'SOURCE_SPEC — TLC publishes the list.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'completeness', 'service_zone_not_blank', 0.0, 0.0, 5, FALSE,
     'Column service zone is NULL or trims to an empty string.',
     'SOURCE_SPEC — a blank label reads as a real category in a group-by.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'completeness', 'silver_at_recorded', 0.0, 0.0, 5, FALSE,
     'Lineage column silver_at is NULL.',
     'PIPELINE_INVARIANT — records when the row was last cleaned.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'completeness', 'source_file_recorded', 0.0, 0.0, 5, FALSE,
     'Lineage column source_file is NULL.',
     'PIPELINE_INVARIANT — without it a row cannot be traced to a file and cannot be re-loaded.', 'FLAG', 'rows in the batch'),
    ('silver', 'taxi_zones_clean', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'FLAG', 'scalar (1)'),
    ('silver', 'taxi_zones_clean', 'business', 'two_unknown_zones_present', 0.0, 0.0, 5, FALSE,
     'Ids 264 and 265 are not both present.',
     'SOURCE_SPEC — they are how an unresolvable pickup stays joinable instead of becoming a NULL that drops out of an inner join.', 'FLAG', 'scalar (1)'),
    ('silver', 'taxi_zones_clean', 'completeness', 'zone_name_not_blank', 0.0, 0.0, 5, FALSE,
     'Column zone name is NULL or trims to an empty string.',
     'SOURCE_SPEC — a blank label reads as a real category in a group-by.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'business', 'all_expected_days_present', 0.0, 0.0, 5, FALSE,
     'A day in the covered months has no weather rows.',
     'PIPELINE_INVARIANT — a gap in the hourly series.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'apparent_temp_parsed', 10.0, 0.0, 5, FALSE,
     'Value of apparent temp was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'validity', 'cloud_cover_0_to_100', 10.0, 0.0, 5, FALSE,
     'Cloud cover is outside 0-100.',
     'SOURCE_SPEC — it is a percentage.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'cloud_cover_parsed', 10.0, 0.0, 5, FALSE,
     'Value of cloud cover was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'consistency', 'description_known_for_code', 10.0, 0.0, 5, FALSE,
     'A weather code has no mapped description.',
     'SOURCE_SPEC — tolerated: the cleaning already WARNs and keeps the row. A code outside the CASE is the source using a value we have not mapped, not a broken transformation.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'consistency', 'description_matches_code', 0.0, 0.0, 5, FALSE,
     'The stored description disagrees with its code mapping.',
     'PIPELINE_INVARIANT — CASE drift, same class as the denormalised labels in Gold.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'dq_status_in_domain', 0.0, 0.0, 5, TRUE,
     'dq_status holds a value outside PASS/WARN/FAIL.',
     'PIPELINE_INVARIANT — a fourth value silently escapes every downstream filter.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'completeness', 'dq_status_populated', 0.0, 0.0, 5, TRUE,
     'dq_status is NULL.',
     'PIPELINE_INVARIANT — Gold filters on it; a NULL classifies as nothing.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'consistency', 'fail_rows_carry_a_fail_issue', 0.0, 0.0, 5, TRUE,
     'A FAIL row names no FAIL: issue.',
     'PIPELINE_INVARIANT — the row is quarantined with no stated reason.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'consistency', 'gusts_at_least_wind_speed', 10.0, 0.0, 5, FALSE,
     'Wind gust is below sustained wind speed.',
     'SOURCE_SPEC — physically impossible; a gust is a peak.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'hour_parsed', 0.0, 0.0, 0, FALSE,
     'The date was present in Bronze and weather_hour is NULL in Silver.',
     'PIPELINE_INVARIANT — a genuine parse loss, separated from a source gap.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'validity', 'hour_within_covered_months', 100.0, 0.0, 5, FALSE,
     'An hour falls outside the months this table covers.',
     'ADVISORY — the weather feed is UTC and the project is New York, so boundary hours legitimately land either side. Worth seeing, not gating on.', 'IGNORE', 'rows in the batch'),
    ('silver', 'weather_clean', 'consistency', 'no_rows_invented_from_bronze', 0.0, 0.0, 5, FALSE,
     'Silver holds a weather hour Bronze does not.',
     'PIPELINE_INVARIANT — the transform may drop or keep, never invent.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'consistency', 'null_hours_are_quarantined', 0.0, 0.0, 5, TRUE,
     'A row whose hour did not parse does not carry the FAIL label.',
     'PIPELINE_INVARIANT — the cleaning KEEPS an unparseable hour and labels it. The promise is the label, not "the hour is never NULL".', 'QUARANTINE', 'rows in the batch'),
    ('silver', 'weather_clean', 'uniqueness', 'one_row_per_hour', 0.0, 0.0, 0, TRUE,
     'More than one row for the same hour.',
     'PIPELINE_INVARIANT — the hour is the MERGE key. No row floor: one duplicate is the defect.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'consistency', 'pass_rows_carry_no_issues', 0.0, 0.0, 5, TRUE,
     'A PASS row has a non-empty issue array.',
     'PIPELINE_INVARIANT — can only fail if the classification CASE is wrong.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'precip_probability_0_to_100', 10.0, 0.0, 5, FALSE,
     'Precipitation probability is outside 0-100.',
     'SOURCE_SPEC — it is a percentage.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'precip_probability_parsed', 10.0, 0.0, 5, FALSE,
     'Value of precip probability was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'completeness', 'qc_array_not_null', 0.0, 0.0, 5, TRUE,
     'qc_error_descriptions is NULL rather than an empty array.',
     'PIPELINE_INVARIANT — NULL and empty behave differently in exists() and size().', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'qc_entries_carry_severity_prefix', 0.0, 0.0, 5, TRUE,
     'An issue entry starts with neither FAIL: nor WARN:.',
     'PIPELINE_INVARIANT — a forgotten prefix silently downgrades a FAIL row to WARN. Seven characters, invisible without this check.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'rain_not_negative', 10.0, 0.0, 5, FALSE,
     'Rain is below zero.',
     'SOURCE_SPEC — physically impossible.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'rain_parsed', 10.0, 0.0, 5, FALSE,
     'Value of rain was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'completeness', 'silver_at_recorded', 0.0, 0.0, 5, FALSE,
     'Lineage column silver_at is NULL.',
     'PIPELINE_INVARIANT — records when the row was last cleaned.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'completeness', 'source_file_month_is_real', 100.0, 0.0, 5, FALSE,
     'source_file_month is NULL or not a parseable month.',
     'PIPELINE_INVARIANT — lineage for the weather feed.', 'IGNORE', 'rows in the batch'),
    ('silver', 'weather_clean', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'FLAG', 'scalar (1)'),
    ('silver', 'weather_clean', 'validity', 'temperature_parsed', 10.0, 0.0, 5, FALSE,
     'Value of temperature was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'validity', 'temperature_plausible', 10.0, 0.0, 5, FALSE,
     'Temperature is outside a plausible range for New York.',
     'OBSERVED — catches a unit swap between C and F.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'visibility_parsed', 10.0, 0.0, 5, FALSE,
     'Value of visibility was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'consistency', 'warn_rows_carry_only_warn_issues', 0.0, 0.0, 5, TRUE,
     'A WARN row carries a FAIL: issue, or none at all.',
     'PIPELINE_INVARIANT — a mislabelled row is in Gold being counted.', 'FLAG', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'weather_code_parsed', 10.0, 0.0, 5, FALSE,
     'Value of weather code was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'completeness', 'weather_hour_populated', 100.0, 0.0, 5, FALSE,
     'weather_hour is NULL, for any reason.',
     'ADVISORY — the count, for information. The promise is null_hours_are_quarantined.', 'IGNORE', 'rows in the batch'),
    ('silver', 'weather_clean', 'validity', 'wind_gusts_parsed', 10.0, 0.0, 5, FALSE,
     'Value of wind gusts was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
    ('silver', 'weather_clean', 'validity', 'wind_speed_parsed', 10.0, 0.0, 5, FALSE,
     'Value of wind speed was present in Bronze and is NULL in Silver — a parse loss, not a source gap.',
     'PIPELINE_INVARIANT — measured against Bronze by joining on date, so a blank cell in the CSV is not counted as a parse failure.', 'FLAG', 'rows comparable against Bronze'),
-- ---------- gold ----------
    ('gold', 'dim_date', 'completeness', 'date_key_not_null', 0.0, 0.0, 0, TRUE,
     'date_key is NULL.',
     'PIPELINE_INVARIANT — the calendar primary key.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'uniqueness', 'date_key_unique', 0.0, 0.0, 0, TRUE,
     'Duplicate date_key in the calendar.',
     'PIPELINE_INVARIANT — a duplicate multiplies rows in every query joining to it.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'consistency', 'date_parts_match_full_date', 0.0, 0.0, 5, FALSE,
     'year or month disagrees with full_date.',
     'PIPELINE_INVARIANT — every attribute is a pure function of full_date.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'completeness', 'full_date_not_null', 0.0, 0.0, 5, FALSE,
     'full_date is NULL in the calendar.',
     'PIPELINE_INVARIANT — the join column for both date foreign keys.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'consistency', 'is_weekend_matches_day_of_week', 0.0, 0.0, 5, FALSE,
     'is_weekend disagrees with day_of_week IN (1, 7).',
     'PIPELINE_INVARIANT — dayofweek() is 1=Sunday..7=Saturday in Spark, NOT ISO. A weekend test written IN (6,7) gives Friday and Saturday.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'consistency', 'key_matches_full_date', 0.0, 0.0, 5, TRUE,
     'date_key disagrees with yyyyMMdd of full_date.',
     'PIPELINE_INVARIANT — two queries joining by different routes return different answers and neither looks wrong.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'completeness', 'no_missing_days', 0.0, 0.0, 5, TRUE,
     'The calendar has a gap between its first and last date.',
     'PIPELINE_INVARIANT — a hole silently drops every trip on that day from any inner join. The build checks this in a SELECT nobody reads.', 'N/A', 'rows in the table'),
    ('gold', 'dim_date', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'N/A', 'scalar (1)'),
    ('gold', 'dim_taxi_zone', 'completeness', 'borough_not_blank', 0.0, 0.0, 5, FALSE,
     'Column borough is NULL or trims to an empty string.',
     'SOURCE_SPEC — a blank label reads as a real category in a group-by.', 'N/A', 'rows in the table'),
    ('gold', 'dim_taxi_zone', 'validity', 'location_id_in_range', 0.0, 0.0, 5, FALSE,
     'location_id is outside 1-265.',
     'SOURCE_SPEC — the published id range.', 'N/A', 'rows in the table'),
    ('gold', 'dim_taxi_zone', 'completeness', 'location_id_not_null', 0.0, 0.0, 0, TRUE,
     'Column location id is NULL.',
     'SOURCE_SPEC — the column is required for the row to be usable downstream.', 'N/A', 'rows in the table'),
    ('gold', 'dim_taxi_zone', 'uniqueness', 'location_id_unique', 0.0, 0.0, 0, TRUE,
     'Duplicate location_id in the lookup.',
     'PIPELINE_INVARIANT — the lookup is a primary key or it is nothing. No row floor.', 'N/A', 'rows in the table'),
    ('gold', 'dim_taxi_zone', 'business', 'lookup_has_265_zones', 0.0, 0.0, 5, FALSE,
     'The zone lookup does not hold exactly 265 rows.',
     'SOURCE_SPEC — TLC publishes 265 zones. A different number is a source change.', 'N/A', 'scalar (1)'),
    ('gold', 'dim_taxi_zone', 'consistency', 'rows_reconcile_with_silver', 0.0, 0.0, 5, FALSE,
     'Gold row count differs from the expected count over Silver.',
     'PIPELINE_INVARIANT — recomputes the build trip_key expression rather than trusting it.', 'N/A', 'scalar (1)'),
    ('gold', 'dim_taxi_zone', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'N/A', 'scalar (1)'),
    ('gold', 'dim_taxi_zone', 'business', 'unknown_zones_present', 0.0, 0.0, 5, FALSE,
     'Ids 264 and 265 are not both present in the dimension.',
     'SOURCE_SPEC — same reserved ids, checked after the copy into Gold.', 'N/A', 'scalar (1)'),
    ('gold', 'dim_taxi_zone', 'completeness', 'zone_name_not_blank', 0.0, 0.0, 5, FALSE,
     'Column zone name is NULL or trims to an empty string.',
     'SOURCE_SPEC — a blank label reads as a real category in a group-by.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'consistency', 'hour_temp_within_day_range', 0.0, 0.0, 5, FALSE,
     'An hourly temp_avg_c falls outside its own day min/max.',
     'PIPELINE_INVARIANT — temp_max/min are the DAY values from a window; temp_avg is the HOUR value. A window over the wrong partition shows up here and nowhere else.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'consistency', 'key_matches_timestamp', 0.0, 0.0, 5, TRUE,
     'weather_key disagrees with yyyyMMddHH of weather_timestamp.',
     'PIPELINE_INVARIANT — same derived-key risk.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'uniqueness', 'one_row_per_hour', 0.0, 0.0, 0, FALSE,
     'More than one row for the same hour.',
     'PIPELINE_INVARIANT — the hour is the MERGE key. No row floor: one duplicate is the defect.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'validity', 'rain_hours_in_domain', 100.0, 0.0, 5, FALSE,
     'rain_hours holds a value other than 0, 1 or NULL.',
     'ADVISORY — the column is typed DOUBLE and named as a count of hours, but the build emits a per-row flag. Recorded so the mismatch is visible, not discovered in a dashboard.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'N/A', 'scalar (1)'),
    ('gold', 'dim_weather', 'consistency', 'timestamp_is_on_the_hour', 0.0, 0.0, 5, FALSE,
     'weather_timestamp has a non-zero minute or second.',
     'PIPELINE_INVARIANT — the build truncates to the hour.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'completeness', 'weather_condition_not_null', 0.0, 0.0, 5, FALSE,
     'weather_condition is NULL.',
     'PIPELINE_INVARIANT — the build COALESCEs to Unknown, so this is a regression test.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'consistency', 'weather_date_matches_timestamp', 0.0, 0.0, 5, FALSE,
     'weather_date disagrees with the date of weather_timestamp.',
     'PIPELINE_INVARIANT — derived column, same risk as the keys.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'completeness', 'weather_key_not_null', 0.0, 0.0, 0, TRUE,
     'weather_key is NULL in the dimension.',
     'PIPELINE_INVARIANT — the dimension primary key.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'uniqueness', 'weather_key_unique', 0.0, 0.0, 0, TRUE,
     'Duplicate weather_key in the dimension.',
     'PIPELINE_INVARIANT — same fan-out risk as any duplicated dimension key.', 'N/A', 'rows in the table'),
    ('gold', 'dim_weather', 'completeness', 'weather_timestamp_not_null', 0.0, 0.0, 5, FALSE,
     'weather_timestamp is NULL in the dimension.',
     'PIPELINE_INVARIANT — the key is derived from it.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'completeness', 'created_at_recorded', 0.0, 0.0, 5, FALSE,
     'Audit column created_at is NULL.',
     'PIPELINE_INVARIANT — records when the fact row first landed.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'business', 'dedup_collapse_rate', 100.0, 0.0, 5, FALSE,
     'Share of Silver rows absorbed by the coarser fact trip_key.',
     'ADVISORY — the early warning for the concat_ws NULL-skipping weakness.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'dropoff_date_matches_timestamp', 0.0, 0.0, 5, TRUE,
     'dropoff_date disagrees with DATE(lpep_dropoff_datetime).',
     'PIPELINE_INVARIANT — a trip starting at 23:50 ends on the next day.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'duration_matches_timestamps', 0.0, 0.0, 5, TRUE,
     'trip_duration_minutes disagrees with its own timestamps.',
     'PIPELINE_INVARIANT — recomputed with unix_timestamp(), not timestampdiff(). The two disagree by exactly the DST shift on trips straddling 02:00 on spring-forward day.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'completeness', 'every_silver_month_present', 0.0, 0.0, 5, FALSE,
     'A month present in Silver has no trips in the fact table.',
     'PIPELINE_INVARIANT — this is what makes "Gold covers all batches" an assertion. An anti-join, not a count comparison: two months can match on count and be the wrong two.', 'N/A', 'distinct months in Silver'),
    ('gold', 'fact_taxi_trip', 'uniqueness', 'one_row_per_trip_key', 0.0, 0.0, 0, TRUE,
     'More than one fact row for the same trip_key.',
     'PIPELINE_INVARIANT — the grain of the fact table, stated.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'payment_type_matches_id', 0.0, 0.0, 5, FALSE,
     'The denormalised payment label disagrees with its id.',
     'PIPELINE_INVARIANT — same CASE-drift risk.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'pickup_before_dropoff', 0.0, 0.0, 5, FALSE,
     'Dropoff timestamp precedes pickup.',
     'BUSINESS_RULE — a reversed trip is not a trip.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'pickup_date_matches_timestamp', 0.0, 0.0, 5, TRUE,
     'pickup_date disagrees with DATE(lpep_pickup_datetime).',
     'PIPELINE_INVARIANT — pickup_date is the foreign key to dim_date.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'business', 'quarantined_rows_in_gold', 100.0, 0.0, 5, FALSE,
     'Fact rows Silver classified FAIL.',
     'ADVISORY BY DESIGN — the fact table deliberately keeps them and carries the labels. What matters is that consumers filter; see the valid-view note in gold_qc.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'ratecode_description_matches_id', 0.0, 0.0, 5, FALSE,
     'The denormalised ratecode label disagrees with its id.',
     'PIPELINE_INVARIANT — same CASE-drift risk.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'revenue_preserved', 0.0, 0.0, 5, TRUE,
     'Total revenue differs between layers beyond 0.1% or $1.',
     'PIPELINE_INVARIANT — a row count can match while values shift. Money is the check that notices.', 'N/A', 'scalar (1)'),
    ('gold', 'fact_taxi_trip', 'consistency', 'rows_reconcile_with_silver', 0.0, 0.0, 5, TRUE,
     'Gold row count differs from the expected count over Silver.',
     'PIPELINE_INVARIANT — recomputes the build trip_key expression rather than trusting it.', 'N/A', 'scalar (1)'),
    ('gold', 'fact_taxi_trip', 'completeness', 'table_not_empty', 0.0, 0.0, 5, TRUE,
     'The table has no rows for this batch.',
     'PIPELINE_INVARIANT — the only check that reports emptiness. Every other check SKIPs on an empty batch rather than inventing its own failure from a NULL aggregate.', 'N/A', 'scalar (1)'),
    ('gold', 'fact_taxi_trip', 'validity', 'trip_key_inputs_not_null', 10.0, 0.0, 5, FALSE,
     'A row has a NULL among the seven trip_key inputs.',
     'PIPELINE_INVARIANT — concat_ws SKIPS NULLs rather than rendering them, so the key becomes ambiguous and two trips can collide. Fix: COALESCE each argument in the MERGE.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'trip_key_matches_its_inputs', 0.0, 0.0, 5, TRUE,
     'The stored trip_key does not match a hash of its own row.',
     'PIPELINE_INVARIANT — recomputed with the build exact expression, NULL-skipping included, so it tests the key rather than disagreeing with it.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'completeness', 'trip_key_not_null', 0.0, 0.0, 0, TRUE,
     'trip_key is NULL.',
     'PIPELINE_INVARIANT — the grain of the fact table.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'trip_type_description_matches_id', 0.0, 0.0, 5, FALSE,
     'The denormalised trip type label disagrees with its id.',
     'PIPELINE_INVARIANT — same CASE-drift risk.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'business', 'trips_carrying_silver_warnings', 100.0, 0.0, 5, FALSE,
     'Fact rows carrying at least one issue entry.',
     'ADVISORY — a level to watch.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'vendor_name_matches_id', 0.0, 0.0, 5, FALSE,
     'The denormalised vendor label disagrees with vendor_id.',
     'PIPELINE_INVARIANT — a dashboard grouped by the label after someone edits the CASE reads as a real change in the business.', 'N/A', 'rows in the table'),
    ('gold', 'fact_taxi_trip', 'consistency', 'weather_key_matches_pickup_hour', 0.0, 0.0, 5, FALSE,
     'The stored weather_key disagrees with the UTC hour of pickup.',
     'PIPELINE_INVARIANT — the ONLY automated statement in the pipeline that the UTC-vs-New-York conversion runs in the right direction. Backwards, every trip still gets a weather row, just the wrong one.', 'N/A', 'rows in the table'),
-- ---------- at_rest ----------
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'calendar_days_used_by_a_trip', 100.0, 0.0, 0, FALSE,
     'Calendar days no trip references.',
     'AT_REST ADVISORY — same reachability signal.', 'N/A', 'rows in the dimension'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'dropoff_date_resolves', 10.0, 0.0, 5, FALSE,
     'A trip dropoff_date has no row in dim_date.',
     'AT_REST — same convention, same denominator reasoning.', 'N/A', 'distinct key values in the fact table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'dropoff_zone_resolves', 0.0, 0.0, 5, TRUE,
     'A distinct dropoff_location_id has no row in dim_taxi_zone.',
     'AT_REST — same, on the other side of the trip.', 'N/A', 'distinct key values in the fact table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'pickup_date_resolves', 10.0, 0.0, 5, FALSE,
     'A trip pickup_date has no row in dim_date.',
     'AT_REST — counted in TRIPS, not distinct dates, and tolerated. dim_date spans the weather feed; TLC files carry a handful of trips dated years outside the file month, which is ~8% of ~100 dates but 0.008% of 133,367 trips.', 'N/A', 'distinct key values in the fact table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'pickup_zone_resolves', 0.0, 0.0, 5, TRUE,
     'A distinct pickup_location_id has no row in dim_taxi_zone.',
     'AT_REST — counted in DISTINCT KEYS. One unmatched zone affecting 40,000 trips is ONE thing to fix; reporting it as 40,000 failures buries it. No row floor for that reason.', 'N/A', 'distinct key values in the fact table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'trips_with_unmatched_dropoff_zone', 100.0, 0.0, 0, FALSE,
     'Trips whose dropoff zone does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'N/A', 'rows in the table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'trips_with_unmatched_pickup_zone', 100.0, 0.0, 0, FALSE,
     'Trips whose pickup zone does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'N/A', 'rows in the table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'trips_with_unmatched_weather_key', 100.0, 0.0, 0, FALSE,
     'Trips whose weather_key does not resolve, in rows.',
     'ADVISORY — the blast radius of the key-level check.', 'N/A', 'rows in the table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'trips_without_weather', 100.0, 0.0, 0, FALSE,
     'Trips with no weather_key at all.',
     'ADVISORY — not a broken reference: the build LEFT JOIN found no hour. Expected at month edges, and the number to watch when the UTC conversion is in question.', 'N/A', 'rows in the table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'weather_hours_used_by_a_trip', 100.0, 0.0, 0, FALSE,
     'Dimension hours no trip references.',
     'AT_REST ADVISORY — an unused row is normal; MOST rows unused means the key convention drifted and the join is succeeding on a shrinking subset.', 'N/A', 'rows in the dimension'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'weather_key_resolves', 0.0, 0.0, 5, FALSE,
     'A non-NULL weather_key has no row in dim_weather.',
     'AT_REST — NOT blocking: the cause is a stale fact table, not corrupt data, and a rebuild clears it. Blocking does not rebuild anything.', 'N/A', 'distinct key values in the fact table'),
    ('at_rest', 'fact_taxi_trip', 'at_rest_integrity', 'zones_used_by_a_trip', 100.0, 0.0, 0, FALSE,
     'Zones no trip references.',
     'AT_REST ADVISORY — same reachability signal.', 'N/A', 'rows in the dimension');


-- # 2. Read-back
--
-- The shape of what just landed, so a wrong count is visible immediately
-- rather than in a dashboard three days later.

SELECT layer,
       COUNT(*)                                              AS rules,
       SUM(CASE WHEN blocking THEN 1 ELSE 0 END)             AS blocking,
       SUM(CASE WHEN threshold_pct = 0   THEN 1 ELSE 0 END)  AS strict,
       SUM(CASE WHEN threshold_pct = 100 THEN 1 ELSE 0 END)  AS advisory,
       SUM(CASE WHEN min_failed_rows = 0 THEN 1 ELSE 0 END)  AS no_row_floor
FROM   nyc_quality.dq_rules
GROUP  BY layer
ORDER  BY CASE layer WHEN 'preload' THEN 0 WHEN 'bronze' THEN 1
                     WHEN 'silver'  THEN 2 WHEN 'gold'   THEN 3 ELSE 4 END;

-- What can actually stop each layer, named.
SELECT layer, table_name,
       concat_ws(', ', collect_list(check_name)) AS blocking_checks
FROM   nyc_quality.dq_rules
WHERE  blocking
GROUP  BY layer, table_name
ORDER  BY layer, table_name;


-- # 3. Drift — the reason this notebook exists
--
-- A catalogue is only worth reading if it is true. These two queries compare
-- dq_rules against what the notebooks actually emitted into dq_results, in
-- both directions:
--
--   * **documented, never run** -- a rule in this table that no run has
--     produced. Either the check was renamed or removed and the catalogue was
--     not, or the layer has not been run since the rule was added.
--   * **run, never documented** -- a check writing results that this table
--     does not describe. Someone added a check and did not catalogue it.
--
-- Run this after every full pipeline pass. Expect zero rows from both.
--
-- Scoped to the most recent run of each layer, so a rule added today is not
-- reported as drift against results from last week.

CREATE OR REPLACE TEMPORARY VIEW vw_latest_emitted AS
WITH latest AS (
    SELECT layer, MAX(run_ts) AS max_ts
    FROM   nyc_quality.dq_results
    GROUP  BY layer
)
SELECT DISTINCT d.layer, d.table_name, d.check_name
FROM   nyc_quality.dq_results d
JOIN   latest l ON d.layer = l.layer AND d.run_ts = l.max_ts
WHERE  d.check_category <> 'gate';

-- Documented here, not produced by the latest run of that layer.
SELECT r.layer, r.table_name, r.check_name, 'documented, never run' AS drift
FROM       nyc_quality.dq_rules r
LEFT  JOIN vw_latest_emitted e
       ON  e.layer = r.layer AND e.table_name = r.table_name
       AND e.check_name = r.check_name
WHERE  e.check_name IS NULL
  -- Only layers that have actually run; an unrun layer is not drift.
  AND  r.layer IN (SELECT DISTINCT layer FROM vw_latest_emitted)

UNION ALL

-- Produced by the latest run, not documented here.
SELECT e.layer, e.table_name, e.check_name, 'run, never documented'
FROM       vw_latest_emitted e
LEFT  JOIN nyc_quality.dq_rules r
       ON  e.layer = r.layer AND e.table_name = r.table_name
       AND e.check_name = r.check_name
WHERE  r.check_name IS NULL

ORDER  BY drift, layer, table_name, check_name;


-- Thresholds that disagree between the catalogue and the run. The notebooks
-- are the source of truth; a row here means this table needs regenerating.
SELECT d.layer, d.table_name, d.check_name,
       r.threshold_pct AS catalogued, d.threshold_pct AS ran,
       r.min_failed_rows AS catalogued_floor, d.min_failed_rows AS ran_floor
FROM   nyc_quality.dq_results d
JOIN   nyc_quality.dq_rules   r
       ON  r.layer = d.layer AND r.table_name = d.table_name
       AND r.check_name = d.check_name
JOIN  (SELECT layer, MAX(run_ts) AS max_ts FROM nyc_quality.dq_results GROUP BY layer) l
       ON  d.layer = l.layer AND d.run_ts = l.max_ts
WHERE  d.check_category <> 'gate'
  AND (r.threshold_pct   <> d.threshold_pct
    OR r.min_failed_rows <> d.min_failed_rows)
ORDER  BY d.layer, d.table_name, d.check_name;


-- # 4. The catalogue, joined to the latest result
--
-- One view for the dashboard: every rule, what it means, and how it did on
-- the most recent run of its layer. This is what turns a status column into
-- something a reviewer can act on without opening a notebook.

CREATE OR REPLACE VIEW nyc_quality.vw_dq_catalogue AS
WITH latest AS (
    SELECT layer, MAX(run_ts) AS max_ts
    FROM   nyc_quality.dq_results
    GROUP  BY layer
)
SELECT
    r.layer, r.table_name, r.check_category, r.check_name,
    r.rule_description, r.rationale,
    r.threshold_pct, r.warn_pct, r.min_failed_rows,
    r.blocking, r.silver_action, r.denominator_scope,
    d.status, d.failed_rows, d.total_rows, d.failed_pct,
    d.batch_month, d.run_ts
FROM       nyc_quality.dq_rules r
LEFT  JOIN latest l  ON l.layer = r.layer
LEFT  JOIN nyc_quality.dq_results d
       ON  d.layer = r.layer AND d.table_name = r.table_name
       AND d.check_name = r.check_name AND d.run_ts = l.max_ts;

-- Everything that is not PASS on the latest run, with its reasoning attached.
SELECT layer, table_name, check_name, status,
       failed_rows, total_rows, failed_pct, threshold_pct, min_failed_rows,
       blocking, rule_description, rationale
FROM   nyc_quality.vw_dq_catalogue
WHERE  status IS NOT NULL AND status <> 'PASS'
ORDER  BY CASE status WHEN 'FAIL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END,
          blocking DESC, failed_pct DESC;
